// MTK — hanya objek fisik yang muncul di soal (alat peraga, alat ukur, benda konteks soal cerita).
// Sengaja TIDAK dibuat: diagram/grafik/tabel (akurasi angka Gemini tidak bisa dipercaya → pakai SVG di app),
// dan uang kertas Rupiah realistis (risiko pemalsuan; Gemini juga menolak).
const G = 'FRONT = a face-on view of one face; BACK = opposite face; LEFT/RIGHT = rotated 90°; camera slightly above mid-height so top edges are visible';
const g = (o) => ({ bab: 'mtk-04', f: G, ...o });
const ACR = 'Precision educational geometry model made of crystal-clear transparent acrylic, all edges (rusuk) highlighted with thin solid dark-blue edge lines, every vertex (titik sudut) marked with a small solid red sphere, faces perfectly flat and polished with subtle refraction.';

export default [
  // ---------- MTK 01–02 Bilangan & pecahan ----------
  { bab: 'mtk-01', id: 'sempoa', name: 'Sempoa / abakus', sub: '01a', kw: 'sempoa|abakus|nilai tempat', en: 'a wooden soroban abacus', d: 'Dark hardwood frame with 13 vertical rods, a horizontal divider beam, one upper bead and four lower beads per rod, polished rhombus-shaped beads with wood grain.', v: 1 },
  { bab: 'mtk-01', id: 'pizza-pecahan', name: 'Pizza dipotong (pecahan)', sub: '02a–02d, 02j', v: 1, top: true, kw: 'pizza|martabak|kue|dipotong|potongan', en: 'a round pizza cut into 8 equal slices with one slice pulled slightly away', d: 'Golden baked crust, tomato sauce, melted mozzarella with browning, basil leaves; 8 perfectly equal wedge cuts from the center.' },
  { bab: 'mtk-01', id: 'cokelat-batang', name: 'Cokelat batang berpetak (pecahan)', sub: '02a–02d', v: 1, kw: 'cokelat|coklat', en: 'a milk chocolate bar with a 3×4 grid of 12 equal squares, some squares broken off', d: 'Glossy tempered chocolate with clean molded grooves, 3 squares broken off lying beside it showing snap texture. Unbranded, no wrapper.' },
  { bab: 'mtk-01', id: 'kue-bolu-pecahan', name: 'Kue bolu/tart dipotong', sub: '02a–02d', v: 1, kw: 'bolu|tart|brownies|roti', en: 'a round layered sponge cake cut into equal slices with one slice removed', d: 'Round cake with white frosting top, one wedge taken out revealing soft yellow sponge layers and jam filling; cut surfaces show fine crumb texture.' },
  { bab: 'mtk-01', id: 'kelereng-kantong', name: 'Kelereng berwarna (FPB/KPK, pembagian kelompok)', sub: '01f, 01g, 01k, 07k', v: 1, kw: 'kelereng|manik', en: 'a small pile of glass marbles in three colors next to an open cloth drawstring bag', d: 'Glossy transparent glass marbles with colorful swirls inside — red, blue and green groups — realistic reflections and refractions; a beige cotton drawstring bag.' },

  // ---------- MTK 03 Geometri datar ----------
  { bab: 'mtk-03', id: 'bangun-datar-set', name: 'Bangun datar (keping akrilik)', sub: '03a', v: 1, top: true, set: true, kw: 'persegi|segitiga|jajar genjang|jajargenjang|trapesium|layang|belah ketupat|lingkaran', en: 'flat 5 mm-thick colored acrylic shape tiles arranged in a neat grid', d: 'Exactly nine shapes: square, rectangle, equilateral triangle, right triangle, parallelogram, trapezoid, kite, rhombus, circle. Solid translucent colors (red, orange, yellow, green, teal, blue, purple, pink, grey), polished edges.' },
  { bab: 'mtk-03', id: 'tangram', name: 'Tangram kayu', sub: '03j, 03k, 08e', v: 1, top: true, kw: 'tangram|potongan|bangun gabungan', en: 'a wooden tangram puzzle assembled into a square', d: 'Seven painted wooden pieces (two large triangles, one medium triangle, two small triangles, one square, one parallelogram) each a different color, fitted perfectly into a square, visible wood grain through the paint.' },
  { bab: 'mtk-03', id: 'alat-geometri-set', name: 'Alat geometri: busur derajat, jangka, penggaris segitiga', sub: '03l, 03m', v: 1, set: true, kw: 'busur derajat|busur|jangka|penggaris segitiga', en: 'a school geometry set arranged in a tidy row', d: 'Exactly four, unbranded: a clear 180° protractor with fine degree ticks (numbers blurred), a metal compass with pencil lead, a 45° set square and a 30-60° set square in clear acrylic.' },
  { bab: 'mtk-03', id: 'jam-analog', name: 'Jam dinding analog (sudut jarum jam)', sub: '03l, 05e, 05f', v: 1, kw: '\\bjam\\b|jarum jam|pukul', en: 'a round analog wall clock', d: 'White face with 12 bold hour markers as simple bars (no numerals), 60 minute ticks, black hour and minute hands, thin red second hand, silver metal rim, glass cover with soft reflection. Hands set at 3:00 exactly.' },
  { bab: 'mtk-03', id: 'geoboard', name: 'Geoboard (papan paku)', sub: '03b–03h', v: 1, top: true, kw: 'geoboard|papan berpaku|petak|persegi satuan', en: 'a wooden geoboard with a 7×7 grid of pegs and colored rubber bands', d: 'Square light wooden board with evenly spaced metal pegs; colored rubber bands stretched to form a triangle, a rectangle and a trapezoid.' },
  { bab: 'mtk-03', id: 'benda-lingkaran-set', name: 'Benda berbentuk lingkaran (roda, piring, koin, tutup)', sub: '03e, 03i', v: 1, set: true, kw: 'roda|piring|diameter|jari-jari|keliling lingkaran', en: 'everyday circular objects arranged in a tidy row, unbranded', d: 'Exactly four: a white ceramic plate, a bicycle wheel with spokes, a round jar lid, a plain metal washer.' },

  // ---------- MTK 04 Geometri ruang (model akrilik) ----------
  g({ id: 'kubus', name: 'Kubus', sub: '04a, 04b, 04g', kw: 'kubus', en: 'a cube', d: ACR + ' 6 congruent square faces, 12 equal edges, 8 vertices.' }),
  g({ id: 'balok', name: 'Balok', sub: '04a, 04c, 04h', kw: 'balok', en: 'a rectangular cuboid (length : width : height = 3 : 2 : 1.5)', d: ACR + ' 6 rectangular faces in 3 congruent pairs, 12 edges, 8 vertices.' }),
  g({ id: 'prisma-segitiga', name: 'Prisma segitiga', sub: '04a, 04d, 04i', kw: 'prisma', en: 'a right triangular prism lying on one rectangular face', d: ACR + ' Two congruent triangular end faces, three rectangular side faces, 9 edges, 6 vertices.' }),
  g({ id: 'limas-segiempat', name: 'Limas segiempat', sub: '04a, 04d, 04i', kw: 'limas|piramida', en: 'a square-based pyramid', d: ACR + ' Square base, four congruent triangular side faces meeting at one apex, 8 edges, 5 vertices.' }),
  g({ id: 'limas-segitiga', name: 'Limas segitiga (tetrahedron)', sub: '04a, 04d', kw: 'limas segitiga|bidang empat', en: 'a triangular pyramid (regular tetrahedron)', d: ACR + ' Four equilateral triangle faces, 6 edges, 4 vertices.' }),
  g({ id: 'tabung', name: 'Tabung', sub: '04a, 04e, 04j', kw: 'tabung|silinder', en: 'a right circular cylinder standing upright', d: 'Precision educational geometry model made of crystal-clear transparent acrylic; top and bottom circular faces outlined with thin solid dark-blue lines, a thin dashed-look etched line showing the height; curved side surface polished with realistic refraction. 3 faces (2 circles + 1 curved), 2 curved edges, no vertices.' }),
  g({ id: 'kerucut', name: 'Kerucut', sub: '04a, 04f', kw: 'kerucut', en: 'a right circular cone standing on its base', d: 'Precision educational geometry model made of crystal-clear transparent acrylic; circular base outlined with a thin dark-blue line, apex marked with a small red sphere, curved lateral surface polished. 2 faces, 1 curved edge, 1 apex.' }),
  g({ id: 'bola', name: 'Bola (bangun ruang)', sub: '04a, 04f', kw: 'volume bola|luas permukaan bola|berbentuk bola|jari-jari bola|belahan bola', en: 'a perfect sphere', d: 'Precision educational geometry model made of crystal-clear transparent acrylic with a thin etched great-circle line around the equator and a tiny red dot at the center visible through the acrylic (center point), realistic refraction.', v: 1 }),
  g({ id: 'bangun-ruang-set', name: 'Set semua bangun ruang (perbandingan)', sub: '04a', v: 1, set: true, kw: 'bangun ruang', en: 'a complete set of solid geometry models arranged in a tidy row', d: 'Exactly eight solid painted-wood models in different colors: cube, cuboid, triangular prism, square pyramid, triangular pyramid, cylinder, cone, sphere. Smooth satin paint, sharp edges, visible wood grain on unpainted base faces.' }),
  g({ id: 'jaring-jaring-kubus', name: 'Jaring-jaring kubus (karton terbuka)', sub: '04k', v: 1, kw: 'jaring-jaring', en: 'a cube net cut from thick white cardstock, lying flat, next to a half-folded version', d: 'Left: flat cross-shaped net of six squares with crisp fold creases. Right: the same net partially folded into a cube, showing how faces meet. Paper fiber texture.' }),
  g({ id: 'kubus-satuan', name: 'Kubus satuan disusun (volume)', sub: '04b, 04c, 04l, 08b', v: 1, kw: 'kubus satuan|kubus kecil|disusun|tumpukan', en: 'a stack of interlocking unit cubes forming a 4×3×2 rectangular block, plus a few loose cubes', d: 'Bright plastic snap-cubes in several colors (red, blue, yellow, green) with connector nubs, stacked into a neat cuboid; three loose single cubes beside it.' }),
  g({ id: 'akuarium', name: 'Akuarium balok (kapasitas)', sub: '04c, 04m, 05d', kw: 'akuarium|bak mandi|kolam', en: 'an empty rectangular glass aquarium', d: 'Clear glass panels with thin black silicone seams and black plastic top and bottom rims, filled three-quarters with crystal-clear water showing a flat water surface line. No fish, no decorations.', f: 'FRONT = long glass face; BACK = opposite long face; LEFT/RIGHT = short end faces' }),
  g({ id: 'benda-bangun-ruang-set', name: 'Benda sehari-hari berbentuk bangun ruang', sub: '04a, 04m', v: 1, set: true, kw: 'kaleng|dadu|kardus|tumpeng|toren|drum|es krim', en: 'everyday objects shaped like geometric solids arranged in a tidy row, all unbranded', d: 'Exactly seven: a plain tin can (cylinder), a plain cardboard box (cuboid), a 3×3 colored puzzle cube, a traditional Indonesian tumpeng rice cone, a waffle ice cream cone, a basketball (sphere), a plain triangular-prism cardboard gift box.' }),
  g({ id: 'tandon-air', name: 'Tandon / toren air (tabung)', sub: '04e, 04m, 05i', kw: 'tandon|toren|tangki|drum', en: 'a cylindrical plastic water storage tank', d: 'Upright ribbed blue polyethylene water tank with screw-top manhole lid, outlet valve near the bottom, molded reinforcement rings. Unbranded.' }),

  // ---------- MTK 05 Pengukuran ----------
  { bab: 'mtk-05', id: 'alat-ukur-panjang-set', name: 'Alat ukur panjang: penggaris, meteran gulung, meteran jahit, jangka sorong', sub: '05a', v: 1, set: true, kw: 'penggaris|mistar|meteran|jangka sorong|panjang', en: 'length-measuring tools arranged in a tidy row, unbranded', d: 'Exactly four: a 30 cm clear plastic ruler, a yellow retractable steel tape measure with a tab pulled out, a soft tailor\'s measuring tape loosely coiled, a stainless steel vernier caliper. Fine tick marks, all numbers blurred/unreadable.' },
  { bab: 'mtk-05', id: 'timbangan-set', name: 'Alat ukur berat: timbangan dapur, badan, neraca, dacin', sub: '05b', v: 1, set: true, kw: 'timbangan|neraca|dacin', en: 'weighing instruments arranged in a tidy row, unbranded', d: 'Exactly five: a digital kitchen scale with blank display, a bathroom scale, a traditional equal-arm brass market balance (neraca pasar) with two pans, a steelyard (dacin) with hanging hook and sliding weight, a set of brass standard weights in a wooden box.' },
  { bab: 'mtk-05', id: 'anak-timbangan', name: 'Anak timbangan (1 kg, 500 g, 1 ons…)', sub: '05b', v: 1, kw: 'anak timbangan|ons|kuintal', en: 'a set of cast-iron and brass market weights arranged by size', d: 'Row of cylindrical brass weights with knob tops from large to small plus two larger hexagonal cast-iron weights with handles; no stamped numbers visible.' },
  { bab: 'mtk-05', id: 'wadah-volume-set', name: 'Wadah volume: liter, mL, sendok takar, ember', sub: '05d', v: 1, set: true, kw: 'liter|ml|cc|sendok takar|ember', en: 'volume containers arranged in a tidy row, unbranded', d: 'Exactly five: a 1-liter clear plastic measuring jug with graduations (numbers blurred), a set of measuring spoons, a 600 mL clear water bottle (no label), a 10-liter plastic bucket, a small 5 mL medicine cup.' },
  { bab: 'mtk-05', id: 'keran-debit', name: 'Keran air mengalir ke ember (debit)', sub: '05i, 05j', v: 1, kw: 'debit|keran|kran|mengalir|selang', en: 'a chrome water faucet pouring a steady stream into a bucket', d: 'Chrome wall tap (only a short pipe stub, no wall) with a smooth laminar clear water stream frozen in motion falling into a blue plastic bucket half full with ripples and bubbles.' },
  { bab: 'mtk-05', id: 'jam-tangan-kalender', name: 'Alat ukur waktu: jam tangan, jam pasir, kalender meja', sub: '05e, 05f', v: 1, set: true, kw: 'jam pasir|kalender|jam tangan|detik|menit|windu|abad|dasawarsa', en: 'time-keeping objects arranged in a tidy row, unbranded', d: 'Exactly three: an analog wristwatch with leather strap (no numerals), a wooden-framed hourglass with white sand mid-flow, a blank spiral desk calendar with empty grid (no readable text).' },
  { bab: 'mtk-05', id: 'speedometer', name: 'Speedometer (kecepatan km/jam)', sub: '05g, 05h', v: 1, kw: 'speedometer|km/jam|kecepatan', en: 'a motorcycle analog speedometer gauge cluster', d: 'Round gauge with glowing white tick marks, orange needle, small odometer window (digits blurred), black bezel and chrome rim.' },
  { bab: 'mtk-05', id: 'kendaraan-set', name: 'Kendaraan soal kecepatan: mobil, motor, bus, kereta', sub: '05g, 05k, 05l', v: 1, set: true, kw: 'mobil|motor|bus|kereta|truk|pesawat', en: 'scale die-cast models of vehicles arranged in a tidy row, all unbranded, no license plate text', d: 'Exactly five, side profile, same scale relative to each other: a white family car, a red scooter motorcycle, a green intercity bus, a blue-white commuter train car, a yellow delivery truck.' },

  // ---------- MTK 06 Aritmetika sosial ----------
  { bab: 'mtk-06', id: 'belanja-set', name: 'Barang belanja (untung, rugi, diskon)', sub: '06a–06d, 06j', v: 1, set: true, kw: 'harga|membeli|menjual|diskon|untung|rugi|toko|pedagang', en: 'everyday Indonesian shopping goods arranged in a tidy row, all unbranded, blank labels', d: 'Exactly seven: a woven plastic shopping basket, a 5 kg sack of rice, a bunch of bananas, a carton of eggs, a folded school uniform shirt, a plain pair of sneakers, a blank white price tag with string.' },
  { bab: 'mtk-06', id: 'celengan', name: 'Celengan (tabungan, bunga)', sub: '06e', kw: 'celengan|tabungan|menabung|bunga tunggal|bunga bank|bank', en: 'a ceramic piggy bank', d: 'Glossy pink glazed ceramic pig with a coin slot on top, painted eyes, curly tail; a small stack of plain unmarked golden coins beside it.' },
  { bab: 'mtk-06', id: 'peta-skala', name: 'Peta & penggaris skala', sub: '06i', v: 1, top: true, kw: 'skala|peta|denah', en: 'a folded paper topographic-style map partially unfolded with a clear ruler on top', d: 'Map shows colored terrain, blue rivers and roads with no readable place names or text; a transparent 20 cm ruler laid across it.' },
  { bab: 'mtk-06', id: 'maket-rumah', name: 'Maket rumah (skala/perbandingan)', sub: '06i', kw: 'maket', en: 'an architectural scale model of a simple Indonesian house', d: 'White foam-board and balsa model of a single-storey house with gabled terracotta-textured roof, windows, door, small porch, on a thin white base.' },

  // ---------- MTK 07 Statistika & peluang ----------
  { bab: 'mtk-07', id: 'dadu', name: 'Dadu (peluang)', sub: '07k, 07l', kw: 'dadu', en: 'a pair of standard six-sided dice', d: 'White opaque dice with slightly rounded corners and drilled black pips; opposite faces sum to 7; one die tilted to show three faces.', f: 'FRONT = face with 1 pip toward the camera; BACK = 6 pips; LEFT = 3 pips; RIGHT = 4 pips' },
  { bab: 'mtk-07', id: 'koin-peluang', name: 'Koin (angka & gambar)', sub: '07k, 07l', v: 1, set: true, kw: 'koin|uang logam|mata uang', en: 'two generic silver coins, one showing each side', d: 'Fictional nickel coins (not any real currency): left side shows an embossed stylized flower motif (gambar), right shows an embossed simple abstract star pattern (angka side, no digits). Milled edges, metallic sheen.' },
  { bab: 'mtk-07', id: 'spinner', name: 'Roda putar / spinner', sub: '07k', v: 1, top: true, kw: 'spinner|roda putar|diputar', en: 'a game spinner disc with 8 equal colored sectors and a center arrow', d: 'Round white plastic board, 8 equal sectors (red, orange, yellow, green, teal, blue, purple, pink), black arrow pointer on a center pivot.' },
  { bab: 'mtk-07', id: 'kartu-bernomor', name: 'Kartu bernomor & kantong bola warna', sub: '07k, 07l', v: 1, set: true, kw: 'kartu|bola merah|bola biru|kantong|diambil acak', en: 'a fan of blank playing-style cards and a clear bag of colored balls', d: 'Left: a neat fan of blank white cards with rounded corners (no printed numbers). Right: a transparent plastic bag holding 5 red, 3 blue and 2 yellow ping-pong balls.' },

  // ---------- MTK 08 Pola & aljabar ----------
  { bab: 'mtk-08', id: 'batang-korek-pola', name: 'Pola batang korek api', sub: '08b, 08e', v: 1, top: true, kw: 'korek api|batang korek|lidi', en: 'wooden matchsticks arranged into a growing pattern of 1, 2 and 3 joined squares', d: 'Three separate groups in a row: one square, two joined squares, three joined squares, made of wooden matchsticks with red heads, visible wood grain.' },
  { bab: 'mtk-08', id: 'timbangan-aljabar', name: 'Timbangan seimbang (persamaan aljabar)', sub: '08f, 08g, 08j', v: 1, kw: 'timbangan seimbang|persamaan', en: 'an equal-arm balance scale in equilibrium with cubes and a mystery bag', d: 'Classic brass balance with two pans level: left pan holds a small closed paper bag plus 2 wooden cubes, right pan holds 5 identical wooden cubes. Fine brass engraving.' },
  { bab: 'mtk-08', id: 'susunan-pola-bola', name: 'Pola bilangan segitiga/persegi (susunan bola)', sub: '08a–08e', v: 1, top: true, kw: 'pola|susunan|bilangan segitiga|bilangan persegi', en: 'glossy wooden beads arranged into triangular number patterns', d: 'Four separate groups in a row: triangles of 1, 3, 6 and 10 beads, each bead a polished natural-wood sphere touching its neighbors.' },
];
