// IPA 02 — Tubuh Manusia & Kesehatan. Organ = model anatomi realistis (bersih, tanpa darah).
const O = 'FRONT = anterior (as seen facing the person); BACK = posterior; LEFT/RIGHT = the organ\'s own left and right lateral sides';
const a = (o) => ({ bab: 'ipa-02', s: 'anat', f: O, ...o });
const m = (o) => ({ bab: 'ipa-02', s: 'micro', ...o });
const x = (o) => ({ bab: 'ipa-02', ...o });

export default [
  // ---------- Pencernaan ----------
  a({ id: 'sistem-pencernaan', name: 'Sistem pencernaan lengkap', sub: '02a', kw: 'pencernaan|kerongkongan|lambung|usus', en: 'a complete human digestive system anatomical model, isolated organs only (no torso shell)', d: 'In correct anatomical arrangement: mouth/tongue and salivary glands at top, pharynx, long muscular esophagus, J-shaped stomach, large reddish-brown liver with green gallbladder, pancreas behind the stomach, coiled small intestine (duodenum, jejunum, ileum), large intestine framing it (ascending, transverse, descending colon), cecum with appendix, rectum. Moist pink-red mucosal tissue, visible blood vessels on surfaces.' }),
  a({ id: 'gigi-jenis-set', name: 'Jenis gigi: seri, taring, geraham kecil, geraham besar', sub: '02a', v: 1, set: true, kw: 'gigi', en: 'four individual human permanent teeth with roots, arranged in one row', d: 'Exactly four: (1) chisel-shaped incisor (gigi seri) with one root, (2) pointed canine (taring) with long single root, (3) upper premolar (geraham kecil) with two cusps and two roots, (4) upper molar (geraham besar) with broad four-cusped crown and three roots. All from the upper jaw. Glossy off-white enamel crown, yellowish cementum-covered roots.' }),
  a({ id: 'gigi-penampang', name: 'Penampang gigi (email, dentin, pulpa)', sub: '02a', v: 1, kw: 'email|dentin|pulpa|gigi', en: 'a human molar tooth cut lengthwise (cross-section model)', d: 'Showing white glossy enamel, cream-yellow dentin, pink pulp cavity with red and blue vessels and a yellow nerve running down the root canals, cementum, and a slice of pink gum and bone around the roots.' }),
  a({ id: 'lidah', name: 'Lidah (indera pengecap)', sub: '02a, 02e', kw: 'lidah|pengecap|papila', en: 'a human tongue anatomical model', d: 'Pink moist muscular tongue with visible papillae texture (filiform, fungiform dots, V-shaped row of large circumvallate papillae at the back), median sulcus down the center; underside with frenulum and veins.', f: 'FRONT = top (dorsal) surface facing camera; BACK = underside; LEFT/RIGHT = side profiles' }),
  a({ id: 'lambung', name: 'Lambung', sub: '02a', kw: 'lambung|maag|pepsin|asam lambung', en: 'a human stomach anatomical model with a window cut into the front wall', d: 'J-shaped muscular organ with the esophagus entering at the cardia and the duodenum leaving at the pylorus; outer smooth pink serosa with blood vessels; the cut window reveals the thick rugae folds of the inner mucosa and layered muscle walls.' }),
  a({ id: 'hati-empedu', name: 'Hati & kantong empedu', sub: '02a, 02d', kw: '\\bhati\\b|empedu', en: 'a human liver with gallbladder anatomical model', d: 'Large wedge-shaped reddish-brown liver with right and left lobes and falciform ligament, glossy capsule; underside showing the pear-shaped green gallbladder, bile ducts, portal vein and hepatic artery.' }),
  a({ id: 'pankreas', name: 'Pankreas', sub: '02a, 02k', kw: 'pankreas|insulin', en: 'a human pancreas with duodenum anatomical model', d: 'Elongated lobulated pale pink-tan gland (head nestled in the C-curve of the duodenum, body, tail), bumpy glandular texture, pancreatic duct joining the bile duct.' }),
  a({ id: 'usus-halus-besar', name: 'Usus halus & usus besar (dengan umbai cacing)', sub: '02a', kw: 'usus|umbai cacing|apendiks|apendisitis|vili', en: 'human small and large intestines anatomical model', d: 'Coiled pink small intestine loops in the center framed by the wider haustrated large intestine (colon) with its pouches, cecum with the worm-like appendix, rectum. Mesentery with fine vessels.' }),
  m({ id: 'vili-usus', name: 'Vili usus halus (jonjot penyerapan)', sub: '02a', v: 1, kw: 'vili|jonjot|penyerapan', en: 'a magnified 3D block of the small-intestine wall showing villi', d: 'Finger-like villi projecting from the mucosa, one villus cut open showing the capillary network (red/blue) and central lacteal (white), columnar epithelial cells with microvilli brush border.' }),

  // ---------- Pernapasan ----------
  a({ id: 'sistem-pernapasan', name: 'Sistem pernapasan (laring → paru-paru)', sub: '02b', kw: 'pernapasan|paru-paru|trakea|bronkus|tenggorok', en: 'a human respiratory system anatomical model, isolated organs only', d: 'Larynx with cartilage, ringed trachea (C-shaped cartilage rings) that STOPS exactly where it splits into the left and right main bronchi -- nothing continues down between the lungs below that split -- then branching bronchi equally visible inside BOTH spongy pink lungs (right with 3 lobes, left with 2 lobes and cardiac notch), and a THIN dome-shaped sheet of diaphragm muscle directly under both lungs like a shallow umbrella (never a bulging pouch or sac). Front lung partly cut away to reveal branching bronchioles.' }),
  a({ id: 'paru-paru', name: 'Paru-paru', sub: '02b', kw: 'paru-paru', en: 'a pair of healthy human lungs with trachea', d: 'Spongy, soft pink lungs with fine mottled texture and faint grey marbling, 3 lobes right, 2 lobes left with cardiac notch, pleura sheen, ringed trachea and main bronchi at top.' }),
  m({ id: 'alveolus', name: 'Alveolus (pertukaran O₂ & CO₂)', sub: '02b', v: 1, kw: 'alveol(?:us|i)|pertukaran gas', en: 'a cluster of lung alveoli at the end of a bronchiole', d: 'Grape-like cluster of thin-walled air sacs, one cut open, wrapped by a dense net of red (oxygenated) and blue (deoxygenated) capillaries.' }),
  a({ id: 'insang-ikan', name: 'Insang ikan (alat napas hewan)', sub: '02b', v: 1, kw: 'insang', en: 'the gill arches of a fish, dissected cleanly', d: 'Four bony gill arches, each with rows of bright red feathery gill filaments and white gill rakers on the inner side; fine lamellae visible.' }),

  // ---------- Peredaran darah ----------
  a({ id: 'jantung', name: 'Jantung (luar)', sub: '02c', kw: 'jantung|aorta|serambi|bilik', en: 'a human heart anatomical model with great vessels', d: 'Fist-sized cone-shaped muscular heart, apex pointing down toward the person\'s LEFT (which appears on the viewer\'s RIGHT in the front view); coronary arteries and veins on the surface, fat deposits along grooves, aorta arching up, pulmonary trunk, superior and inferior vena cava, pulmonary veins. Moist red-brown myocardium; arteries tinted red, veins tinted blue.' }),
  a({ id: 'jantung-penampang', name: 'Penampang jantung (4 ruang & katup)', sub: '02c', v: 1, kw: 'serambi|bilik|katup|septum', en: 'a human heart cut in a frontal section anatomical model', d: 'Four chambers clearly visible: right atrium, right ventricle, left atrium, thicker-walled left ventricle; interventricular septum; tricuspid and bicuspid (mitral) valves with chordae tendineae, semilunar valves at the aorta and pulmonary artery.' }),
  a({ id: 'pembuluh-darah-set', name: 'Pembuluh darah: arteri, vena, kapiler', sub: '02c', v: 1, set: true, kw: 'arteri|vena|kapiler|pembuluh', en: 'three short blood vessel segments side by side with cut ends showing their walls', d: 'Exactly three: (1) artery — thick elastic muscular red wall, round lumen, (2) vein — thinner wall, color-coded blue by textbook convention, flattened lumen, one cut open to show a valve, (3) capillary — microscopic single-cell-thick tube (enlarged). Clean cut sections.' }),
  m({ id: 'sel-darah-set', name: 'Sel darah: eritrosit, leukosit, trombosit', sub: '02c', v: 1, set: true, kw: 'eritrosit|leukosit|trombosit|sel darah|keping darah|hemoglobin', en: 'the three kinds of human blood cells side by side', d: 'Exactly three groups: (1) several red blood cells — biconcave discs, no nucleus, (2) one larger white blood cell (neutrophil) with lobed nucleus and irregular surface, (3) several tiny irregular platelet fragments.' }),

  // ---------- Ekskresi ----------
  a({ id: 'sistem-urinaria', name: 'Sistem ekskresi ginjal (ginjal, ureter, kandung kemih)', sub: '02d', kw: 'ginjal|ureter|kandung kemih|uretra|urin', en: 'a human urinary system anatomical model, isolated', d: 'Two bean-shaped red-brown kidneys (the person\'s right kidney sits slightly lower than the left because of the liver) with renal artery (red) and renal vein (blue) connecting to aorta and vena cava segments, two thin ureters descending to a muscular pale-pink urinary bladder, urethra.' }),
  a({ id: 'ginjal-penampang', name: 'Penampang ginjal (korteks, medula, pelvis)', sub: '02d', v: 1, kw: 'ginjal|korteks|medula|nefron|pelvis', en: 'a human kidney cut in half lengthwise', d: 'Outer renal capsule, reddish granular cortex, darker striped triangular medullary pyramids, calyces, pale renal pelvis funneling into the ureter, branching vessels at the hilum.' }),
  m({ id: 'nefron', name: 'Nefron (penyaringan darah)', sub: '02d', v: 1, kw: 'nefron|glomerulus|filtrasi|reabsorpsi', en: 'a single nephron, the kidney\'s filtering unit', d: 'Glomerulus (tuft of red capillaries) inside the cup-shaped Bowman\'s capsule, proximal convoluted tubule, loop of Henle, distal convoluted tubule, collecting duct, surrounding capillary network.' }),
  a({ id: 'kulit-penampang', name: 'Penampang kulit (epidermis, dermis, kelenjar keringat)', sub: '02d, 02e', v: 1, kw: 'kulit|keringat|epidermis|dermis', en: 'a 3D block cross-section of human skin', d: 'Layered block: epidermis with dead-cell surface, dermis with hair follicles and hair shafts, sebaceous glands, coiled sweat glands with ducts to surface pores, arrector pili muscles, touch receptors, nerves, blood vessels, and yellow fatty subcutaneous layer.' }),

  // ---------- Saraf & indera ----------
  a({ id: 'otak', name: 'Otak (besar, kecil, batang otak)', sub: '02e', kw: 'otak|serebrum|serebelum|sumsum lanjut', en: 'a human brain anatomical model with brainstem', d: 'Pinkish-grey cerebrum with realistic gyri and sulci, two hemispheres divided by the longitudinal fissure, cerebellum with fine folia at the back underside, brainstem (medulla oblongata) extending down.', f: 'FRONT = frontal lobes facing camera; BACK = occipital lobes and cerebellum; LEFT/RIGHT = lateral hemispheres' }),
  m({ id: 'neuron', name: 'Sel saraf (neuron)', sub: '02e', v: 1, kw: 'neuron|sel saraf|akson|dendrit', en: 'a single motor neuron', d: 'Star-shaped cell body with nucleus, branching dendrites, one long axon wrapped in segmented myelin sheath with nodes of Ranvier, branching axon terminals with synaptic knobs.' }),
  a({ id: 'mata', name: 'Bola mata (indera penglihat)', sub: '02e, 04c', kw: '\\bmata\\b|retina|kornea|iris|pupil|lensa mata', en: 'a human eyeball anatomical model with extrinsic muscles', d: 'White sclera with fine red vessels, clear dome-shaped cornea over a brown iris and black pupil, six extraocular muscles attached, optic nerve emerging from the back.', f: 'FRONT = cornea and iris facing camera; BACK = optic nerve; LEFT/RIGHT = side profiles' }),
  a({ id: 'mata-penampang', name: 'Penampang mata', sub: '02e, 04c', v: 1, kw: 'retina|kornea|lensa mata|bintik kuning|saraf optik', en: 'a human eyeball cut in half horizontally', d: 'Cornea, aqueous humor chamber, iris, pupil, biconvex crystalline lens held by ciliary body and suspensory ligaments, clear vitreous humor, red-orange retina lining the back with the yellow spot (fovea) and blind spot where the optic nerve exits, choroid and sclera layers.' }),
  a({ id: 'telinga', name: 'Telinga (luar, tengah, dalam)', sub: '02e, 04e', v: 1, kw: 'telinga|gendang|koklea|rumah siput|tulang pendengaran', en: 'a coronal section of the HEAD through the ear canal, showing outer, middle and inner ear', d: 'Textbook layout: the skin-toned auricle sticks out on the LEFT edge, the ear canal runs horizontally to the RIGHT into the skull, ending at the pearly-grey eardrum. The middle ear (three DISTINCT ossicle shapes -- hammer, anvil, stirrup, not round beads -- plus Eustachian tube) and inner ear (snail-shaped cochlea, three semicircular canals, vestibule, auditory nerve) sit to the RIGHT of the eardrum, INSIDE the surrounding skull bone -- never inside the auricle or earlobe.' }),
  a({ id: 'hidung-penampang', name: 'Penampang hidung (indera pembau)', sub: '02e, 02b', v: 1, kw: 'hidung|pembau|penciuman|olfaktori', en: 'a sagittal section model of the human nasal cavity', d: 'Nostril, nasal hairs, curled turbinates (conchae) with pink mucosa, olfactory epithelium patch at the roof with olfactory bulb and nerve fibers passing through the bone, connection to the pharynx.' }),

  // ---------- Rangka & otot ----------
  a({ id: 'kerangka-manusia', name: 'Kerangka manusia lengkap', sub: '02f', kw: 'k?erangka|rangka|tulang', en: 'a complete adult human skeleton model, standing in anatomical position', d: '206 bones in natural ivory-bone color with realistic porous texture: skull with mandible, spinal column with S-curve, 12 pairs of ribs and sternum, clavicles and scapulae, humerus, radius, ulna, carpals and phalanges, pelvis, femur, patella, tibia, fibula, tarsals, metatarsals. No stand pole visible.', f: 'FRONT = anterior anatomical position, palms forward; BACK = posterior; LEFT/RIGHT = lateral profiles' }),
  a({ id: 'tengkorak', name: 'Tengkorak', sub: '02f', kw: 'tengkorak', en: 'a human skull model', d: 'Ivory bone color, cranial sutures, orbits, nasal cavity, zygomatic arches, full set of teeth in upper jaw and a separate-hinged mandible, foramen magnum visible from below.', f: 'FRONT = face; BACK = occipital; LEFT/RIGHT = lateral profiles' }),
  a({ id: 'tulang-belakang', name: 'Tulang belakang', sub: '02f', kw: 'tulang belakang|ruas|vertebra|skoliosis|lordosis|kifosis', en: 'a full human vertebral column model with sacrum and coccyx', d: '7 cervical, 12 thoracic, 5 lumbar vertebrae with natural S-curve, bluish-white intervertebral discs between them, sacrum and coccyx, spinous and transverse processes.', f: 'FRONT = anterior (vertebral bodies); BACK = spinous processes; LEFT/RIGHT = lateral showing the S-curve' }),
  a({ id: 'tulang-rusuk', name: 'Rongga dada (tulang rusuk & dada)', sub: '02f, 02b', kw: 'rusuk|tulang dada|sternum', en: 'a human rib cage model', d: 'Sternum (manubrium, body, xiphoid), 12 pairs of ribs — 7 true, 3 false, 2 floating — with bluish costal cartilages, thoracic vertebrae at the back.' }),
  a({ id: 'tulang-paha-penampang', name: 'Tulang pipa (femur) & penampangnya', sub: '02f', v: 1, set: true, kw: 'tulang pipa|sumsum|femur|tulang paha', en: 'a human femur model next to a longitudinally cut femur', d: 'Left: whole femur with ball-shaped head, neck, long shaft, knee condyles. Right: same bone sawn lengthwise showing compact bone, spongy bone at the ends, yellow marrow in the central cavity and red marrow in the spongy ends, cartilage caps.' }),
  a({ id: 'sendi-set', name: 'Jenis sendi: peluru, engsel, putar, pelana', sub: '02f', v: 1, set: true, kw: 'sendi', en: 'four human joint models in one row', d: 'Exactly four: (1) ball-and-socket shoulder joint, (2) hinge elbow joint, (3) pivot joint between atlas and axis neck vertebrae, (4) saddle joint at the thumb base. Bone models with bluish cartilage and white ligaments.' }),
  a({ id: 'otot-lengan', name: 'Otot lengan bisep & trisep (antagonis)', sub: '02f', kw: 'bisep|trisep|antagonis|otot', en: 'a human arm muscle anatomical model, flexed at the elbow', d: 'Upper and lower arm bones with striated red biceps (contracted, bulging) on the front and triceps on the back, white shiny tendons attaching to bones, forearm muscles. Realistic muscle fiber striations.', f: 'FRONT = biceps side; BACK = triceps side; LEFT/RIGHT = lateral and medial sides' }),
  m({ id: 'jenis-otot-set', name: '3 jenis otot: lurik, polos, jantung', sub: '02f', v: 1, set: true, kw: 'otot lurik|otot polos|otot jantung|otot rangka', en: 'three types of muscle tissue side by side as magnified 3D fiber bundles', d: 'Exactly three: (1) skeletal (striated) — long cylindrical fibers with stripes and many peripheral nuclei, (2) smooth — spindle-shaped cells with single central nucleus, no stripes, (3) cardiac — branched striated cells with intercalated discs.' }),

  // ---------- Reproduksi & pubertas ----------
  a({ id: 'reproduksi-wanita', name: 'Organ reproduksi wanita (internal)', sub: '02g, 02h', kw: 'rahim|ovarium|indung telur|tuba|uterus|menstruasi', en: 'a medical anatomical model of the internal female reproductive organs only', d: 'Pear-shaped muscular uterus, two fallopian tubes with fringed fimbriae, two oval ovaries with follicles, cervix and upper vagina segment. Neutral clinical textbook model, no external body.', f: 'FRONT = anterior view; BACK = posterior; LEFT/RIGHT = lateral' }),
  a({ id: 'reproduksi-pria', name: 'Organ reproduksi pria (internal, testis & saluran)', sub: '02g, 02h', v: 1, kw: 'testis|sperma|vas deferens|prostat|buah zakar', en: 'a medical anatomical model of the internal male reproductive ducts and glands only', d: 'Clinical textbook model limited to: one oval testis with coiled epididymis, the vas deferens looping upward, seminal vesicle and prostate gland beside a small section of bladder. No external genitalia, no body.' }),
  m({ id: 'sperma-ovum', name: 'Sel kelamin: sperma & ovum (pembuahan)', sub: '02g', v: 1, set: true, kw: 'sperma|ovum|sel telur|pembuahan|zigot', en: 'a human egg cell (ovum) with several sperm cells approaching', d: 'Large round ovum with translucent zona pellucida and radiating corona radiata cells, nucleus visible; several tiny sperm cells with oval heads, midpieces and long tails, one touching the surface.' }),
  a({ id: 'janin-rahim', name: 'Janin dalam rahim (perkembangan)', sub: '02g', v: 1, kw: 'janin|kehamilan|plasenta|tali pusat|embrio', en: 'a medical model of a 20-week fetus inside a sectioned uterus', d: 'Curled fetus in amniotic sac, umbilical cord connecting to the placenta on the uterine wall, uterine muscle cut in section. Gentle, clinical, non-graphic.' }),

  // ---------- Gizi ----------
  x({ id: 'isi-piringku', name: 'Isi Piringku (gizi seimbang)', sub: '02i', v: 1, top: true, kw: 'isi piringku|gizi seimbang|4 sehat|empat sehat', en: 'an Indonesian "Isi Piringku" balanced-meal plate', d: 'Round white ceramic plate divided naturally: one third steamed white rice, one third mixed green vegetables (spinach, carrot, long beans), one sixth protein (a piece of fried tempeh, a boiled egg, grilled fish), one sixth fresh fruit (papaya and banana slices); a clear glass of water beside the plate.', set: true }),
  x({ id: 'sumber-karbohidrat-set', name: 'Sumber karbohidrat', sub: '02i', v: 1, set: true, kw: 'karbohidrat|nasi|singkong|ubi|kentang|roti', en: 'Indonesian carbohydrate-rich foods arranged in a tidy row', d: 'Exactly five: a small mound of steamed white rice, an ear of yellow corn, a cassava root, a purple sweet potato, a loaf slice of white bread. Fresh natural textures.' }),
  x({ id: 'sumber-protein-set', name: 'Sumber protein (hewani & nabati)', sub: '02i', v: 1, set: true, kw: 'protein|tempe|tahu|daging|telur|ikan', en: 'protein-rich foods arranged in a tidy row', d: 'Exactly six: a raw chicken egg, a whole raw mackerel fish, a piece of raw beef, a block of tofu, a block of tempeh, a small heap of green mung beans.' }),
  x({ id: 'sumber-lemak-set', name: 'Sumber lemak', sub: '02i', v: 1, set: true, kw: 'lemak|minyak|mentega|alpukat|santan|kelapa', en: 'fat-rich foods arranged in a tidy row', d: 'Exactly five: a small glass bottle of golden cooking oil, a block of butter, a halved avocado with seed, a halved mature coconut showing white flesh, a handful of peanuts.' }),
  x({ id: 'sumber-vitamin-mineral-set', name: 'Sumber vitamin & mineral', sub: '02i', v: 1, set: true, kw: 'vitamin|mineral|kalsium|zat besi|yodium', en: 'vitamin- and mineral-rich foods arranged in a tidy row', d: 'Exactly seven: an orange cut in half (vit C), carrots with tops (vit A), a glass of milk (calcium, vit D), a bunch of spinach (iron), a halved papaya, a green guava, a small pile of iodized salt crystals in a tiny bowl.' }),

  // ---------- Penyakit & kesehatan ----------
  m({ id: 'virus-dengue', name: 'Virus dengue (DBD)', sub: '02j, 02m', v: 1, kw: 'dbd|dengue|demam berdarah', en: 'a dengue virus particle', d: 'Small spherical virion with a smooth herringbone-patterned envelope of E-protein dimers, cutaway revealing the capsid and RNA genome inside.' }),
  m({ id: 'virus-corona', name: 'Virus SARS-CoV-2 (COVID-19)', sub: '02j', v: 1, kw: 'covid|corona', en: 'a SARS-CoV-2 coronavirus particle', d: 'Spherical lipid envelope covered with club-shaped spike proteins forming a crown, membrane and envelope proteins, cutaway showing coiled RNA wrapped in nucleocapsid.' }),
  m({ id: 'virus-influenza', name: 'Virus influenza', sub: '02j', v: 1, kw: 'influenza|flu\\b', en: 'an influenza virus particle', d: 'Roughly spherical envelope studded with two kinds of spikes (hemagglutinin rods and neuraminidase mushrooms), cutaway showing eight RNA segments.' }),
  m({ id: 'bakteri-tbc', name: 'Bakteri TBC (Mycobacterium tuberculosis)', sub: '02j, 02m', v: 1, kw: 'tbc|tuberkulosis|mycobacterium', en: 'a cluster of Mycobacterium tuberculosis bacilli', d: 'Slender slightly curved rod-shaped bacteria with a thick waxy rough cell wall, some forming cord-like chains.' }),
  x({ id: 'vaksin-suntik', name: 'Vaksin (vial & jarum suntik)', sub: '02j', v: 1, set: true, kw: 'vaksin|imunisasi|suntik', en: 'a glass vaccine vial with a blank white label and a sterile disposable syringe', d: 'Small clear glass vial with aluminum crimp cap and grey rubber stopper, clear liquid inside, completely blank label; a transparent 3 ml plastic syringe with graduated markings (no readable text) and capped needle.' }),
  x({ id: 'masker-medis', name: 'Masker medis', sub: '02j, 02l', kw: 'masker', en: 'a 3-ply disposable surgical face mask', d: 'Light-blue pleated non-woven fabric outer layer with fine fiber texture, white inner layer, flexible nose wire along the top edge, white elastic ear loops.', f: 'FRONT = outer blue face; BACK = inner white face; LEFT/RIGHT = side profiles showing pleats' }),
  x({ id: 'alat-kebersihan-set', name: 'Alat kebersihan diri', sub: '02l', v: 1, set: true, kw: 'sikat gigi|sabun|cuci tangan|pasta gigi|handuk|shampo|gunting kuku', en: 'personal hygiene items arranged in a tidy row', d: 'Exactly six, all unbranded: a toothbrush with soft bristles, a tube of toothpaste (blank tube), a bar of soap with light foam, a folded white towel, a nail clipper, a plain pump bottle of hand soap.' }),
  x({ id: 'tensimeter', name: 'Tensimeter (alat ukur tekanan darah)', sub: '02c, 02k', v: 1, kw: 'tensimeter|tekanan darah|hipertensi|sfigmomanometer', en: 'an aneroid sphygmomanometer with stethoscope', d: 'Grey arm cuff with velcro, round dial gauge with needle (markings unreadable/blurred), rubber bulb with valve, tubing; a stethoscope coiled beside it.' }),
  x({ id: 'glukometer', name: 'Glukometer (alat cek gula darah)', sub: '02k', v: 1, kw: 'gula darah|diabetes|glukometer|glukosa', en: 'a handheld blood glucose meter with a test strip and lancet pen', d: 'Compact white-and-grey meter with blank display screen, one test strip inserted, a lancing pen beside it. Unbranded, clean.' }),
  x({ id: 'stetoskop', name: 'Stetoskop (denyut jantung)', sub: '02c', v: 1, kw: 'stetoskop|denyut|detak', en: 'a medical stethoscope', d: 'Stainless steel dual-sided chest piece with diaphragm and bell, black Y-shaped rubber tubing, chrome binaural ear tubes with soft ear tips, arranged in a neat loop.' }),
  x({ id: 'fermentasi-produk-set', name: 'Produk bioteknologi konvensional', sub: '02n', v: 1, set: true, kw: 'bioteknologi|yoghurt|yogurt|keju|kecap|roti|nata|oncom|acar|asinan', en: 'traditional biotechnology (fermented) food products arranged in a tidy row', d: 'Exactly seven, unbranded: a block of tempeh, a small glass jar of yogurt, a wedge of yellow cheese with holes, a glass of soy sauce in a tiny dish, a loaf of bread, cubes of nata de coco, a small jar of pickles (acar).' }),
];
