// IPA 04 — Cahaya, Bunyi, Panas, Wujud & Sifat Zat, Pemisahan Campuran, Gelombang, Atom.
const t = (o) => ({ bab: 'ipa-04', ...o });

export default [
  // ---------- Cahaya & optik ----------
  t({ id: 'cermin-datar', name: 'Cermin datar', sub: '04b', kw: 'cermin datar', en: 'a rectangular flat mirror in a thin wooden frame on a small stand', d: 'Silvered glass reflecting only a soft neutral light-grey tone (no reflected scene, no people), thin natural wood frame, back shows grey painted backing and a folding stand.', f: 'FRONT = mirror face; BACK = painted backing and stand; LEFT/RIGHT = thin edge profile' }),
  t({ id: 'cermin-cekung-cembung-set', name: 'Cermin cekung & cermin cembung', sub: '04b', v: 1, set: true, kw: 'cermin cekung|cermin cembung|konkaf|konveks', en: 'a concave mirror and a convex mirror side by side on small metal lab stands', d: 'Two round polished optical mirrors of the same size: left concave (curving inward like a bowl, reflection of a soft light enlarged), right convex (bulging outward, reflection small and wide). Chrome edges, black mounts. No people or scenery in reflections.' }),
  t({ id: 'cermin-cembung-jalan', name: 'Cermin cembung di tikungan jalan', sub: '04b', kw: 'tikungan|spion|kaca spion', en: 'a round convex traffic safety mirror on a short pole', d: 'Large round convex mirror with an orange plastic rim and hood, mounted on a grey galvanized pole segment with bracket; reflection shows only blurred sky tones.' }),
  t({ id: 'lensa-cembung-cekung-set', name: 'Lensa cembung & lensa cekung (bentuk penampang)', sub: '04c', v: 1, set: true, kw: 'lensa cembung|lensa cekung|konvergen|divergen', en: 'a biconvex glass lens and a biconcave glass lens standing on edge side by side', d: 'Two crystal-clear optical glass lenses of equal diameter in thin metal rims on small stands: left thick in the middle and thin at the edges, right thin in the middle and thick at the edges. Clear caustic highlights showing their thickness profile.' }),
  t({ id: 'lup', name: 'Lup / kaca pembesar', sub: '04c', kw: '\\blup\\b|kaca pembesar', en: 'a handheld magnifying glass', d: 'Round clear convex glass lens in a polished brass rim with a turned dark wooden handle.', f: 'FRONT = lens facing camera; BACK = reverse side; LEFT/RIGHT = edge profile showing the lens bulge' }),
  t({ id: 'kacamata-minus-plus-set', name: 'Kacamata minus (cekung) & plus (cembung)', sub: '04c, 02e', v: 1, set: true, kw: 'kacamata|miopi|hipermetropi|rabun|presbiopi', en: 'two pairs of eyeglasses side by side', d: 'Left: black rectangular frames with thin-center/thick-edge concave (minus) lenses that make edges look thicker. Right: tortoiseshell round frames with thick-center convex (plus) lenses that slightly magnify. Unbranded.' }),
  t({ id: 'prisma-kaca', name: 'Prisma kaca (penguraian cahaya)', sub: '04d', kw: 'prisma', en: 'a triangular optical glass prism dispersing a thin beam of white light into a rainbow spectrum', d: 'Crystal-clear equilateral glass prism, a thin white beam entering one face and a fan of seven colors (red, orange, yellow, green, blue, indigo, violet) exiting the other side — red is bent the LEAST (closest to the original beam direction) and violet is bent the MOST (toward the prism base).', bg: 'k', v: 1 }),
  t({ id: 'cakram-newton', name: 'Cakram Newton (warna → putih)', sub: '04d', v: 1, kw: 'cakram newton|piringan newton', en: 'a Newton color wheel disc', d: 'Round disc divided into seven equal colored sectors (red, orange, yellow, green, blue, indigo, violet), mounted on a small hand crank spinner with wooden handle.' }),
  t({ id: 'periskop', name: 'Periskop (dua cermin datar)', sub: '04b', kw: 'periskop', en: 'a homemade cardboard periscope with one side cut open', d: 'Tall rectangular brown cardboard tube with two openings at opposite sides of top and bottom; a cutaway window shows the two small flat mirrors mounted parallel at 45 degrees.' }),
  t({ id: 'kamera-lubang-jarum', name: 'Kamera lubang jarum', sub: '04a', kw: 'lubang jarum|pinhole', en: 'a homemade pinhole camera box', d: 'Black cardboard box with a tiny pinhole in aluminum foil on the front and a translucent tracing-paper screen on the back showing a faint upside-down image of a candle flame.' }),
  t({ id: 'mikroskop', name: 'Mikroskop cahaya', sub: '01o, 04c, 06a', kw: 'mikroskop', en: 'a student compound light microscope', d: 'Cream-white metal body with black trim, monocular eyepiece, revolving nosepiece with three objective lenses, stage with slide clips holding a glass slide, coarse and fine focus knobs, mirror/LED illuminator at the base.', f: 'FRONT = objectives and stage facing camera; BACK = arm side; LEFT/RIGHT = side profiles showing focus knobs' }),
  t({ id: 'teropong-bintang', name: 'Teropong bintang (teleskop)', sub: '04c, 05o', kw: 'teropong|teleskop', en: 'a refractor telescope on a tripod', d: 'White tube with dew shield, black eyepiece with star diagonal, small finder scope, altazimuth mount on an aluminum tripod with accessory tray. Unbranded.' }),

  // ---------- Bunyi ----------
  t({ id: 'garpu-tala', name: 'Garpu tala (sumber bunyi)', sub: '04e', kw: 'garpu tala', en: 'a steel tuning fork with its wooden resonance box and rubber mallet', d: 'Polished chrome U-shaped fork with a stem mounted on a hollow wooden resonator box open at one end; small rubber-headed mallet beside it.' }),
  t({ id: 'alat-musik-set', name: 'Alat musik (sumber getaran bunyi)', sub: '04e', v: 1, set: true, kw: 'gitar|gendang|seruling|suling|angklung|gamelan|biola|drum', en: 'Indonesian and common musical instruments arranged in a tidy row', d: 'Exactly five: a bamboo angklung, a bamboo flute (suling), a wooden kendang drum with leather heads, an acoustic guitar, a small bronze gamelan bonang kettle gong.' }),
  t({ id: 'telepon-kaleng', name: 'Telepon kaleng (bunyi merambat di benang)', sub: '04g', v: 1, kw: 'telepon kaleng|telepon benang|kaleng', en: 'a tin-can telephone', d: 'Two clean empty tin cans (no labels) connected by a taut white cotton string threaded through holes in their bases.' }),

  // ---------- Suhu & panas ----------
  t({ id: 'termometer-set', name: 'Jenis termometer: klinis, laboratorium, digital, inframerah', sub: '04h, 06a', v: 1, set: true, kw: 'termometer', en: 'different thermometers arranged in a tidy row, unbranded', d: 'Exactly five: a glass clinical thermometer with silver mercury column, a long glass lab thermometer with red alcohol column, a digital stick thermometer with blank display, an infrared forehead thermometer gun, and a wall dial room thermometer. Scale ticks fine, numbers blurred.' }),
  t({ id: 'termos-penampang', name: 'Termos (mencegah konduksi, konveksi, radiasi)', sub: '04i', v: 1, set: true, kw: 'termos', en: 'a vacuum flask shown whole and cut in half side by side', d: 'Left: an intact stainless steel vacuum flask with cup lid. Right: the same flask cut lengthwise showing double silvered walls, the vacuum gap between them, insulating stopper, and plastic outer casing supports.' }),
  t({ id: 'panci-pegangan', name: 'Panci (konduktor) dengan pegangan isolator', sub: '04i, 03k', kw: 'panci|wajan|pegangan', en: 'an aluminum cooking pot with black bakelite handles and lid', d: 'Brushed aluminum body with fine scratches, glass lid with vent hole, heat-resistant black bakelite side handles and lid knob.' }),
  t({ id: 'perpindahan-panas-set', name: 'Perpindahan panas: sendok di teh panas, air mendidih, api unggun', sub: '04i', v: 1, set: true, kw: 'konduksi|konveksi|radiasi', en: 'three isolated items illustrating heat transfer', d: 'Exactly three: (1) a metal spoon standing in a glass cup of hot tea with steam, (2) a clear glass pot of boiling water with bubbles and visible convection swirl of a few tea leaves, (3) a small campfire of burning logs with flames and glowing embers.', bg: 'k' }),

  // ---------- Wujud zat & perubahan ----------
  t({ id: 'wujud-zat-set', name: 'Wujud zat: padat, cair, gas', sub: '04j', v: 1, set: true, kw: 'wujud|padat|cair|gas', en: 'three items showing the three states of matter side by side', d: 'Exactly three: (1) a solid wooden cube block, (2) a clear glass of orange juice, (3) a transparent glass flask filled with visible pale-brown gas / thin mist with a stopper.' }),
  t({ id: 'es-batu-mencair', name: 'Es batu mencair (mencair)', sub: '04k', v: 1, kw: 'es batu|mencair|membeku', en: 'three clear ice cubes, partly melting with water droplets and a small puddle', d: 'Crystal-clear ice cubes with trapped micro-bubbles and frosty edges, glossy wet surfaces, droplets running down, a small transparent meltwater puddle.' }),
  t({ id: 'mengembun-gelas', name: 'Gelas es berembun (mengembun)', sub: '04k', kw: 'mengembun|embun', en: 'a tall clear glass of ice water with condensation droplets on the outside', d: 'Ice cubes floating, the outside of the glass covered in fine fog and large condensation beads running down.' }),
  t({ id: 'kapur-barus', name: 'Kapur barus / naftalena (menyublim)', sub: '04k', v: 1, kw: 'kapur barus|naftalena|menyublim|kamper', en: 'a small pile of white naphthalene mothballs', d: 'Round white crystalline mothballs with a slightly waxy, sugary surface and tiny crystal facets.', bg: 'k' }),
  t({ id: 'dry-ice', name: 'Es kering / dry ice (menyublim)', sub: '04k', v: 1, kw: 'es kering|dry ice', en: 'a few pellets and a block of dry ice releasing white fog', d: 'Frosty white solid CO₂ block and pellets with thick white vapor rolling off and flowing downward.', bg: 'k' }),
  t({ id: 'perubahan-kimia-set', name: 'Perubahan kimia: besi berkarat, kayu terbakar, apel teroksidasi, telur matang', sub: '04l', v: 1, set: true, kw: 'karat|berkarat|perubahan kimia|membusuk|terbakar', en: 'items showing chemical changes arranged in a tidy row', d: 'Exactly four: a new shiny iron nail next to a heavily rusted orange-brown nail, a half-burnt charred wooden stick, a halved apple turning brown, a fried egg.' }),
  t({ id: 'perubahan-fisika-set', name: 'Perubahan fisika: kertas disobek, gelas pecah, cokelat meleleh', sub: '04l', v: 1, set: true, kw: 'perubahan fisika|disobek|meleleh', en: 'items showing physical changes arranged in a tidy row', d: 'Exactly three: a sheet of white paper torn into pieces, a chocolate bar partly melted, a folded paper airplane beside a flat sheet.' }),

  // ---------- Pemisahan campuran ----------
  t({ id: 'filtrasi', name: 'Penyaringan / filtrasi', sub: '04m', v: 1, kw: 'filtrasi|penyaringan|kertas saring|menyaring', en: 'a laboratory filtration setup', d: 'A glass funnel with folded white filter paper in a ring clamp on a retort stand, muddy brown water being filtered, clear filtrate dripping into an Erlenmeyer flask below, brown residue on the paper.' }),
  t({ id: 'distilasi', name: 'Penyulingan / distilasi', sub: '04m', v: 1, kw: 'distilasi|destilasi|penyulingan|sulingan', en: 'a laboratory simple distillation apparatus', d: 'Round-bottom flask with colored liquid on a tripod over a spirit burner flame, thermometer in the top, thermometer bulb level with the side-arm opening, a Liebig glass condenser angled down with cooling water entering the LOWER rubber tube and leaving the UPPER tube, clear distillate dripping into a receiving flask.' }),
  t({ id: 'kromatografi', name: 'Kromatografi kertas', sub: '04m', v: 1, kw: 'kromatografi', en: 'a paper chromatography setup', d: 'A tall glass beaker with a little clear water, a strip of white filter paper hanging from a pencil laid across the rim; a black washable-ink spot drawn just ABOVE the water level has separated into rising bands of blue, purple, yellow and pink.' }),
  t({ id: 'penguapan-garam', name: 'Penguapan / evaporasi (garam dari air laut)', sub: '04m', v: 1, kw: 'penguapan|evaporasi|kristalisasi|garam', en: 'an evaporating dish on a tripod and gauze over a spirit burner', d: 'White porcelain evaporating dish with a crust of white salt crystals forming as the last water steams off, wire gauze, steel tripod, glass spirit burner flame.' }),
  t({ id: 'larutan-koloid-suspensi', name: 'Larutan, koloid, suspensi (3 gelas)', sub: '04n', v: 1, set: true, kw: 'larutan|koloid|suspensi', en: 'three identical clear glasses side by side', d: 'Exactly three: (1) a clear transparent sugar-water solution, (2) white opaque milk (colloid), (3) muddy water with sand settling to the bottom (suspension) showing sediment layer.' }),
  t({ id: 'efek-tyndall', name: 'Efek Tyndall', sub: '04n', v: 1, kw: 'tyndall', en: 'two glass beakers with a laser-like light beam passing through', d: 'A thin white/red light beam crosses both beakers: in the left (true solution, clear) the beam is invisible inside the liquid; in the right (colloid, slightly milky) the beam path is clearly visible as a glowing line.', bg: 'k' }),

  // ---------- Gelombang & atom ----------
  t({ id: 'slinki', name: 'Slinki (gelombang transversal & longitudinal)', sub: '04o', v: 1, kw: 'slinki|slinky|pegas', en: 'a metal slinky spring toy stretched showing compressions and rarefactions', d: 'Chrome steel coil spring stretched horizontally, some coils bunched together (rapatan) and others spread apart (renggangan). Mirror-like metal reflections.' }),
  t({ id: 'model-atom', name: 'Model atom (inti proton-neutron & elektron)', sub: '04p, 03o', s: 'micro', v: 1, kw: 'atom|proton|neutron|elektron', en: 'a 3D ball-and-orbit model of a carbon atom', d: 'Central nucleus of 6 red spheres (protons) and 6 grey spheres (neutrons) clustered tightly, two thin glowing orbital rings (shells) with 2 small blue electron spheres on the inner shell and 4 on the outer shell.', bg: 'k' }),
];
