// IPA 03 — Gaya, Gerak, Energi, Pesawat Sederhana, Listrik & Magnet. Semua tanpa merek/logo.
const t = (o) => ({ bab: 'ipa-03', ...o });

export default [
  // ---------- Alat ukur & gaya ----------
  t({ id: 'neraca-pegas', name: 'Neraca pegas / dinamometer (satuan Newton)', sub: '03a', kw: 'neraca pegas|dinamometer|newton', en: 'a laboratory spring scale (dynamometer)', d: 'Clear acrylic tube with a visible steel coil spring inside, a sliding red indicator, an engraved scale (fine tick marks, numbers blurred/unreadable), metal top ring and bottom hook with a small hanging 100 g brass slotted mass.', f: 'FRONT = scale face; BACK = rear of the tube; LEFT/RIGHT = side profiles' }),
  t({ id: 'bola-sepak', name: 'Bola sepak (gaya dorong/tendang)', sub: '03a, 03c', kw: 'bola sepak|sepak bola|menendang', en: 'a classic leather soccer ball', d: 'Traditional 32-panel truncated-icosahedron pattern of white hexagons and black pentagons, stitched seams, slight scuffing and grain on synthetic leather. Unbranded.', v: 1 }),
  t({ id: 'plastisin', name: 'Plastisin/tanah liat berubah bentuk (pengaruh gaya)', sub: '03c', v: 1, set: true, kw: 'plastisin|lilin mainan|tanah liat|berubah bentuk', en: 'two lumps of modeling clay, one round ball and one flattened by pressing', d: 'Same bright red modeling clay: left a smooth ball, right the same ball pressed flat into a disc with fingerprints visible on top.' }),
  t({ id: 'ban-berulir', name: 'Ban berulir (manfaat gaya gesek)', sub: '03a, 03c', kw: 'ban|gesek|gaya gesek|ulir', en: 'a new bicycle tire with deep tread pattern', d: 'Black rubber tire with knobby deep tread grooves, fine rubber texture, side wall with molded lines (no text). Upright standing.', f: 'FRONT = tread facing camera; BACK = opposite tread; LEFT/RIGHT = sidewall faces' }),

  // ---------- Momentum ----------
  t({ id: 'momentum-bola-set', name: 'Bola ringan vs bola berat bergerak sama cepat (momentum)', sub: '03m', v: 1, set: true, kw: 'momentum', en: 'two balls of very different mass moving at the same speed, shown side by side with motion-blur streak lines', d: 'Exactly two: left a small light table-tennis ball with a short motion-blur streak trailing behind it; right a large heavy bowling ball rolling with an equally long motion-blur streak (same speed), both moving in the same direction on a plain floor. Same lighting and background for both, no arrows, no text.' }),

  // ---------- Tuas ----------
  t({ id: 'jungkat-jungkit', name: 'Jungkat-jungkit (tuas jenis 1)', sub: '03d', kw: 'jungkat-jungkit', en: 'a playground seesaw', d: 'Long painted wooden plank with two handles and seats at each end, resting on a central metal pivot (fulcrum) stand, slight tilt. Chipped paint, wood grain.', f: 'FRONT = long side facing camera, full length visible; BACK = opposite long side; LEFT/RIGHT = end-on views' }),
  t({ id: 'tuas-jenis-1-set', name: 'Alat tuas jenis 1 (titik tumpu di tengah)', sub: '03d', v: 1, set: true, kw: 'gunting|tang|linggis|catut|tuas jenis 1|jenis pertama|golongan 1|golongan pertama', en: 'first-class lever tools arranged in a tidy row', d: 'Exactly four, unbranded: a pair of steel scissors (opened slightly), combination pliers with insulated grips, a steel crowbar, a claw hammer. Realistic metal machining marks and wear.' }),
  t({ id: 'tuas-jenis-2-set', name: 'Alat tuas jenis 2 (beban di tengah)', sub: '03d', v: 1, set: true, kw: 'gerobak|pembuka botol|pemecah kemiri|pelubang kertas|tuas jenis 2|jenis kedua|golongan 2|golongan kedua', en: 'second-class lever tools arranged in a tidy row', d: 'Exactly four, unbranded: a metal bottle opener, a nutcracker, a lever-arm paper cutter (guillotine trimmer with the hinge at one end), and a small wheelbarrow model with one wheel.' }),
  t({ id: 'tuas-jenis-3-set', name: 'Alat tuas jenis 3 (kuasa di tengah)', sub: '03d', v: 1, set: true, kw: 'pinset|sekop|sapu|joran|pancing|stapler|staples|tuas jenis 3|jenis ketiga|golongan 3|golongan ketiga', en: 'third-class lever tools arranged in a tidy row', d: 'Exactly four, unbranded: a pair of stainless steel tweezers, a garden spade/shovel with wooden handle, a long-handled broom, a bamboo fishing rod with line.', note: 'Stapler sengaja tidak dimasukkan: buku pelajaran berbeda-beda menggolongkannya (jenis 2 atau 3), jadi berisiko menyesatkan.' }),
  t({ id: 'gerobak-dorong', name: 'Gerobak dorong / arco (tuas jenis 2)', sub: '03d', kw: 'gerobak|arco', en: 'a construction wheelbarrow', d: 'Galvanized steel tray with slight scratches and dried cement dust, single pneumatic front wheel, two long steel handles with rubber grips, tubular support legs.' }),

  // ---------- Katrol ----------
  t({ id: 'katrol-tetap', name: 'Katrol tetap (timba sumur)', sub: '03e', kw: 'katrol|kerekan|sumur|timba', en: 'a traditional well pulley assembly: a fixed pulley wheel hanging from a short wooden beam, rope, and a bucket', d: 'Cast-iron grooved pulley wheel with axle in a steel bracket bolted under a short wooden crossbeam, thick natural hemp rope over the groove, one end tied to a galvanized metal bucket, the other end hanging free.' }),
  t({ id: 'katrol-bergerak', name: 'Katrol bergerak', sub: '03e', v: 1, kw: 'katrol bergerak|katrol bebas', en: 'a laboratory movable pulley demonstration setup', d: 'Metal lab clamp stand with a horizontal rod; rope anchored to the rod, running down under a single movable pulley (the pulley carries a hook with a cylindrical 1 kg iron mass) and back up to a hand-free loop end. Clean physics-lab hardware.' }),
  t({ id: 'katrol-majemuk', name: 'Katrol majemuk / takal', sub: '03e', v: 1, kw: 'katrol majemuk|takal|katrol ganda|block', en: 'a block-and-tackle compound pulley system', d: 'Two steel pulley blocks each with two sheaves, threaded with thick nylon rope (4 supporting strands), upper block with hook, lower block with hook carrying a heavy iron weight.' }),

  // ---------- Bidang miring ----------
  t({ id: 'bidang-miring-papan', name: 'Bidang miring (papan landai)', sub: '03f', kw: 'bidang miring|papan|landai|curam', en: 'a wooden inclined-plane ramp with a small wooden cart', d: 'Smooth plywood ramp on a simple wooden support forming a triangle, a small four-wheeled wooden trolley resting halfway up the slope. Visible wood grain and screw heads.', f: 'FRONT = side profile showing the triangle of the slope; BACK = opposite side; LEFT = low end; RIGHT = high end' }),
  t({ id: 'sekrup-baut', name: 'Sekrup, baut & mur (bidang miring melingkar)', sub: '03f', v: 1, set: true, kw: 'sekrup|baut|ulir|dongkrak', en: 'steel fasteners arranged in a tidy row', d: 'Exactly four: a long wood screw with sharp helical thread, a hex bolt with fine machine thread, a matching hex nut, and a car scissor jack (small). Zinc-plated metal sheen, machining detail.' }),
  t({ id: 'baji-set', name: 'Baji: kapak, pisau, pahat, paku', sub: '03f', v: 1, set: true, kw: 'kapak|pisau|pahat|baji|paku', en: 'wedge-shaped cutting tools arranged in a tidy row', d: 'Exactly four, unbranded: a wood-handled axe, a kitchen knife, a wood chisel, and a steel nail. Sharp edges with honing marks, wood-grain handles.' }),
  t({ id: 'tangga-rumah', name: 'Tangga (bidang miring)', sub: '03f', kw: 'tangga', en: 'an aluminum A-frame step ladder', d: 'Brushed aluminum rails, ribbed anti-slip steps, rubber feet, top platform. Opened in standing position.' }),

  // ---------- Roda berporos ----------
  t({ id: 'sepeda', name: 'Sepeda (roda berporos, roda gigi)', sub: '03g, 03b', kw: 'sepeda', en: 'a classic city bicycle', d: 'Steel frame, spoked wheels with rubber tires, front chainring and rear sprocket connected by a greasy metal chain (clearly visible gear teeth), pedals with cranks, handlebar, saddle, bell, mudguards. Unbranded.', f: 'FRONT = front wheel facing camera; BACK = rear; LEFT/RIGHT = full side profiles (right side shows the chain drive)' }),
  t({ id: 'roda-berporos-set', name: 'Alat roda berporos: setir, obeng, gagang pintu, gerinda', sub: '03g', v: 1, set: true, kw: 'setir|obeng|gagang pintu|kenop|kincir|gerinda|roda berporos', en: 'wheel-and-axle tools arranged in a tidy row', d: 'Exactly four, unbranded: a car steering wheel with column shaft, a flat-head screwdriver, a round brass door knob with spindle, a hand-crank pencil sharpener.' }),

  // ---------- Energi & alat listrik ----------
  t({ id: 'alat-energi-listrik-panas-set', name: 'Listrik → panas: setrika, rice cooker, solder, pemanas air', sub: '03i', v: 1, set: true, kw: 'setrika|magic jar|rice cooker|penanak|solder|pemanas|dispenser', en: 'household electric-to-heat appliances arranged in a tidy row, unbranded', d: 'Exactly four: a steam clothes iron with soleplate, an electric rice cooker, an electric kettle, a soldering iron on its stand. Clean plastic and metal textures, power cords neatly coiled.' }),
  t({ id: 'kipas-angin', name: 'Kipas angin (listrik → gerak)', sub: '03i', kw: 'kipas angin|kipas', en: 'an electric standing desk fan, unbranded', d: 'Round protective wire grille, three transparent blue plastic blades, motor housing, oscillation knob, adjustable neck, round base with speed buttons. Power cord coiled.', f: 'FRONT = grille facing camera; BACK = motor housing; LEFT/RIGHT = side profile' }),
  t({ id: 'lampu-bohlam', name: 'Lampu pijar (bohlam)', sub: '03i, 03j', kw: 'bohlam|lampu pijar|filamen|lampu', en: 'a clear incandescent light bulb, switched off', d: 'Clear glass bulb, visible coiled tungsten filament supported by thin wires on a glass stem, aluminum E27 screw base with black insulator and solder contact tip.' }),
  t({ id: 'lampu-led-cfl-set', name: 'Lampu pijar vs LED vs neon (hemat energi)', sub: '03h, 03i', v: 1, set: true, kw: 'led|hemat energi|neon|tl\\b', en: 'three light bulb types side by side, switched off', d: 'Exactly three, unbranded: a clear incandescent bulb, a spiral compact fluorescent lamp (CFL), and a white frosted LED bulb with aluminum heat-sink neck.' }),
  t({ id: 'senter', name: 'Senter (kimia → listrik → cahaya)', sub: '03i', kw: 'senter', en: 'a handheld flashlight with its battery compartment open', d: 'Black anodized aluminum body with knurled grip, reflector cup and bulb visible through the lens, push switch, tail cap unscrewed showing two AA batteries inside. Unbranded.', f: 'FRONT = lens facing camera; BACK = tail cap; LEFT/RIGHT = side profiles' }),
  t({ id: 'lilin-menyala', name: 'Lilin (kimia → cahaya & panas)', sub: '03i, 04k', kw: 'lilin', en: 'a white pillar candle burning', d: 'Smooth white paraffin candle with a small pool of melted wax around the black wick, realistic teardrop flame with blue base, yellow core, faint wax drips down the side.', bg: 'k' }),
  t({ id: 'speaker-mikrofon-set', name: 'Speaker & mikrofon (listrik ↔ bunyi)', sub: '03i, 04e', v: 1, set: true, kw: 'speaker|pengeras suara|mikrofon|mic', en: 'a raw loudspeaker driver and a handheld dynamic microphone side by side, unbranded', d: 'Left: a round speaker driver with black paper cone, dust cap, rubber surround, steel basket and heavy ring magnet at the back. Right: a dynamic microphone with metal mesh grille and matte black handle.' }),
  t({ id: 'kompor-gas', name: 'Kompor gas (kimia → panas)', sub: '03i', kw: 'kompor', en: 'a two-burner tabletop gas stove, unbranded', d: 'Black enamel top with two cast-iron pan supports, brass burner heads, two chrome control knobs, one burner lit with a ring of blue flames.' }),
  t({ id: 'dinamo-sepeda', name: 'Dinamo sepeda (gerak → listrik)', sub: '03i, 03p', kw: 'dinamo|generator', en: 'a bicycle bottle dynamo with its headlamp', d: 'Chrome cylindrical bottle dynamo with knurled rubber roller cap on top, mounting bracket, thin wire running to a small round chrome bicycle headlamp.' }),
  t({ id: 'panel-surya', name: 'Panel surya (cahaya → listrik)', sub: '03h, 05i', kw: 'panel surya|sel surya|tenaga surya|solar', en: 'a monocrystalline solar panel module', d: 'Dark blue-black silicon cells in a grid with thin silver busbar lines, tempered glass surface with subtle reflections, aluminum frame; the back shows a white backsheet and a small junction box with cables.', f: 'FRONT = cells facing camera; BACK = rear with junction box; LEFT/RIGHT = thin edge profiles' }),
  t({ id: 'kincir-angin', name: 'Kincir angin / turbin angin (gerak → listrik)', sub: '03h, 05i', kw: 'kincir|turbin|pltb|angin', en: 'a scale model of a modern three-blade wind turbine', d: 'Tall white tapered tubular tower, nacelle housing at top, three long slender white blades on the hub. Clean matte paint with fine panel seams.' }),
  t({ id: 'baterai-set', name: 'Baterai & aki (sumber listrik kimia)', sub: '03j', v: 1, set: true, kw: 'baterai|aki|batu baterai|elemen', en: 'electric cells arranged in a tidy row, all blank unbranded labels', d: 'Exactly four: an AA cylindrical battery, a 9V rectangular battery, a coin cell battery, and a small 12V lead-acid car battery (aki) with red and black terminals. Plus/minus terminal shapes visible, no text.' }),

  // ---------- Rangkaian listrik ----------
  t({ id: 'rangkaian-seri', name: 'Rangkaian seri (papan praktikum)', sub: '03j', v: 1, top: true, kw: 'seri', en: 'a real hands-on series circuit built on a wooden board', d: 'On a small wooden baseboard: a holder with two AA batteries, a toggle switch, and three small flashlight bulbs in porcelain holders connected one after another in a single loop with red and black insulated copper wires held by screw terminals. Bulbs glowing dimly.' }),
  t({ id: 'rangkaian-paralel', name: 'Rangkaian paralel (papan praktikum)', sub: '03j', v: 1, top: true, kw: 'paralel', en: 'a real hands-on parallel circuit built on a wooden board', d: 'On a small wooden baseboard: a holder with two AA batteries, a toggle switch, and three small flashlight bulbs in porcelain holders each on its own branch connected across the same two wires (ladder layout) with red and black insulated copper wires. Bulbs glowing brightly.' }),
  t({ id: 'sakelar-stopkontak-set', name: 'Sakelar, stopkontak, steker, sekering/MCB', sub: '03j, 03k', v: 1, set: true, kw: 'sakelar|saklar|stop ?kontak|steker|sekering|mcb|colokan', en: 'household electrical components arranged in a tidy row, unbranded', d: 'Exactly five: a white wall light switch, a white wall socket (Type C/F Indonesian style), a two-pin plug on a short cable, a ceramic cartridge fuse, and a small miniature circuit breaker (MCB).' }),
  t({ id: 'kabel-penampang', name: 'Kabel listrik (konduktor tembaga & isolator)', sub: '03k', v: 1, kw: 'kabel|konduktor|isolator|tembaga', en: 'a short piece of electrical cable with stripped ends', d: 'Grey outer PVC sheath cut back to reveal three colored insulated wires (brown, blue, green-yellow), their ends stripped showing shiny twisted copper strands.' }),
  t({ id: 'konduktor-isolator-set', name: 'Bahan konduktor vs isolator', sub: '03k', v: 1, set: true, kw: 'konduktor|isolator', en: 'common material samples arranged in two groups in one row', d: 'Left group (conductors): an iron nail, a copper coin-like disc, an aluminum spoon, a steel paper clip. Right group (insulators): a wooden stick, a rubber eraser, a plastic ruler, a glass marble, a piece of cloth. Small gap between groups, no labels.' }),

  // ---------- Magnet ----------
  t({ id: 'magnet-bentuk-set', name: 'Bentuk magnet: batang, U/ladam, silinder, cincin, jarum', sub: '03l', v: 1, set: true, kw: 'magnet', en: 'permanent magnets of different shapes arranged in a tidy row', d: 'Exactly five: a red-and-blue painted steel bar magnet, a red horseshoe (U) magnet with silver pole tips, a silver cylindrical neodymium magnet, a black ferrite ring magnet, a thin magnetic compass needle on a pivot. No letters N/S.' }),
  t({ id: 'magnet-serbuk-besi', name: 'Garis gaya magnet (serbuk besi)', sub: '03l', v: 1, top: true, kw: 'garis gaya|serbuk besi|medan magnet', en: 'a bar magnet lying under a thin clear acrylic sheet with iron filings showing magnetic field lines', d: 'Dark grey iron filings arranged in curved lines looping from one pole to the other and radiating densely at the poles, magnet visible through the clear acrylic; filings grainy and metallic.' }),
  t({ id: 'kompas', name: 'Kompas (magnet bumi)', sub: '03l, 05c', kw: 'kompas', en: 'a classic brass magnetic compass', d: 'Polished brass round case with hinged lid open, glass cover, rotating bezel with fine degree ticks (no readable letters), red-and-silver magnetic needle floating on a pivot.', v: 1, top: true }),
  t({ id: 'elektromagnet', name: 'Elektromagnet (paku + kumparan + baterai)', sub: '03l', v: 1, kw: 'elektromagnet|kumparan|lilitan', en: 'a homemade electromagnet', d: 'A large iron nail wrapped tightly with many turns of enamelled red copper wire, the wire ends connected to a D-size battery (blank label), several steel paper clips stuck to the nail tip.' }),
  t({ id: 'bel-listrik', name: 'Bel listrik (penerapan elektromagnet)', sub: '03l', v: 1, kw: 'bel listrik|bel', en: 'an old-style electric bell mechanism with cover removed', d: 'Round chrome gong, spring-mounted iron armature with a small hammer, two copper-wire electromagnet coils, contact screw and terminals on a wooden base.' }),

  // ---------- Tekanan & listrik statis ----------
  t({ id: 'tekanan-hidrostatis-botol', name: 'Tekanan hidrostatis (botol berlubang 3)', sub: '03n', v: 1, kw: 'hidrostatis|kedalaman|lubang', en: 'a tall clear plastic bottle full of water with three holes at different heights, water spurting out', d: 'Show only the first 10–15 cm of each frozen-motion water jet: the bottom jet leaves fastest and flattest, the middle jet slower, the top jet weakest and curving down most steeply (the effect of greater depth = greater pressure); crystal-clear water with realistic droplets. Bottle unlabeled.' }),
  t({ id: 'tekanan-benda-padat-set', name: 'Tekanan zat padat: paku runcing, pisau tajam, sepatu salju', sub: '03n', v: 1, set: true, kw: 'tekanan|runcing|tajam|sepatu salju|luas bidang', en: 'objects illustrating solid pressure arranged in a tidy row', d: 'Exactly four: a sharp steel thumbtack, a sharp chef knife next to a dull butter knife, a wide snowshoe, and a pair of thin high-heel shoes. Clean, unbranded.' }),
  t({ id: 'elektroskop', name: 'Elektroskop (listrik statis)', sub: '03o', kw: 'elektroskop|listrik statis|muatan', en: 'a gold-leaf electroscope', d: 'Glass jar with a wooden/rubber stopper, a vertical brass rod with a polished brass ball on top, and two thin gold leaves at the bottom spread apart (charged).' }),
  t({ id: 'balon-listrik-statis', name: 'Balon & sisir (gosokan listrik statis)', sub: '03o', v: 1, set: true, kw: 'balon|sisir|digosok|penggaris plastik', en: 'static electricity demonstration items', d: 'Exactly three: a red inflated rubber balloon, a plastic comb with small torn paper bits clinging to its teeth, a plastic ruler next to a wool cloth.' }),

  // ---------- Induksi ----------
  t({ id: 'transformator', name: 'Transformator / trafo', sub: '03p', kw: 'trafo|transformator|step', en: 'an educational step-down transformer', d: 'Laminated silicon-steel square iron core with two copper-wire coils — primary coil with many turns and secondary coil with fewer turns — mounted on a base with terminal screws.' }),
  t({ id: 'galvanometer-kumparan', name: 'Induksi: magnet, kumparan & galvanometer', sub: '03p', v: 1, set: true, kw: 'galvanometer|induksi|ggl', en: 'an electromagnetic induction demonstration setup', d: 'A hollow cylindrical coil of copper wire, a bar magnet being inserted into it, wires leading to an analog lab galvanometer whose needle is deflected (scale markings blurred).' }),
];
