// Sumber rujukan per objek.
// w   = judul artikel Wikipedia EN (yang pertama dipakai untuk gambar acuan; link ID diambil otomatis)
// img = override gambar acuan: nama file Wikimedia Commons ('File:...'), dipakai bila gambar utama artikel tidak cocok
// x   = sumber tambahan [judul, url]
// Setelah mengubah file ini: node image-prompts/_src/fetch-acuan.mjs  lalu  node image-prompts/_src/gen.mjs
export default {
  // ================= IPA 01 =================
  'kucing-domestik': { w: ['Cat'], img: ['File:Orange tabby cat sitting on fallen leaves-Hisashi-01A.jpg', 'File:Cat August 2010-4.jpg', 'File:Felis catus-cat on snow.jpg'], only: true },
  'sapi': { w: ['Bali_cattle'], img: ['File:Banteng Domesticated Bali Bull.PNG', 'File:Feeding the Banteng.jpg', 'File:Sapi Bali- Muhammad Syarif.S 11.jpg'], only: true },
  'kelinci': { w: ['Domestic_rabbit'], img: ['File:Heimtier 004 2023 08 26.jpg', 'File:American Grand Champion Dutch Rabbit.jpg', 'File:Lapin Japonais.jpg', 'File:Broken Mini Rex.JPG', 'File:Eithel, black Silver Fox doe.jpg'], only: true },
  'kelelawar-ekolokasi': { w: ['Rhinolophus_affinis', 'Animal_echolocation', 'Horseshoe_bat'], img: ['File:Rhinolophus affinis 86903750.jpg', 'File:Rhinolophus affinis.jpg', 'File:Nose leaf variation of Rhinolophus affinis.webp'], only: true },
  'kelelawar': { w: ['Large_flying_fox'], img: ['File:Polynesian flying fox (Pteropus tonganus) in flight Taveuni.jpg', 'File:Wilhelma Kalong-Flughund Pteropus vampyrus 0513.jpg'], only: true },
  'lumba-lumba': { w: ['Common_bottlenose_dolphin'], img: ['File:Tursiops truncatus 01-cropped.jpg', 'File:010 Atlantic bottlenose dolphin jumping at Pelican point Photo by Giles Laurent.jpg', 'File:Bottlenose Dolphins (1499008891).jpg'], only: true },
  'paus-biru': { w: ['Blue_whale'], img: ['File:Anim1754 - Flickr - NOAA Photo Library.jpg', 'File:Blow of a blue whale in the Arctic sea.jpg'], only: true },
  'ayam': { w: ['Chicken'], img: ['File:Male and female chicken sitting together.jpg', 'File:Junglefowl on tree.jpg', 'File:Thai Game chicken - red 3.JPG'], only: true },
  'telur-ayam': { w: ['Egg_as_food', 'Egg'], img: ['File:Anatomy of an egg unlabeled.svg', 'File:Egg and maxi egg 1.jpg'], only: true },
  'bebek': { w: ['Domestic_duck'], img: ['File:Brown domestic duck with orange beak in a pond at golden hour in Don Det Laos.jpg', 'File:Amerikanische Pekingenten 2013 01c.jpg', 'File:Runner-ducks.jpg'], only: true },
  'elang': { w: ['Javan_hawk-eagle'], img: ['File:ELANG JAWA.jpg', 'File:Javan hawk-eagle (Nisaetus bartelsi).jpg', 'File:Nisaetus bartelsi (Elang Jawa).jpg', 'File:Elang Jawa Nisaetus bartelsi Bandung Zoo 2 cropped.jpg', 'File:Elang Jawa (Nisaetus Bartelsi).jpg'], only: true },
  'katak': { w: ['Fejervarya_limnocharis'], img: ['File:Fejervarya limnocharis (43659333105).jpg', 'File:RBE0516 Fejervarya limnocharis 澤蛙.jpg'], only: true },
  'ikan-mas': { w: ['Common_carp'], img: ['File:Cyprinus carpio 2008 G1 (cropped).jpg', 'File:Two Varieties of Common Carp (Cyprinus carpio).jpg'], only: true },
  'hiu': { w: ['Whale_shark'], img: ['File:Similan Dive Center - great whale shark.jpg', 'File:Oeil et spiracle requin-baleine.JPG', 'File:Whale Shark AdF.jpg', 'File:Male whale shark at Georgia Aquarium.jpg'], only: true },
  'cicak': { w: ['Common_house_gecko'], img: ['File:Common House Gecko with open mouth, in Laos.jpg', 'File:Hemidactylus frenatus dorsal and ventral.jpg', 'File:Common house Gecko caught a prey.jpg'], only: true },
  'bunglon': { w: ['Veiled_chameleon'], img: ['File:Yemen Chameleon.jpg', 'File:C Calyptratus female.jpg', 'File:Jemenchamäleon Chamaeleo calyptratus.jpg', 'File:Jemenchamaeleo maennchen.jpg'], only: true },
  'ular': { w: ['Ptyas_korros'], img: ['File:Ptyas korros- Indochinese rat snake.jpg', 'File:ZamenisKorrosRooij.jpg', 'File:Ptyas korros 60531073.jpg'], only: true },
  'kura-kura': { w: ['Green_sea_turtle'], img: ['File:Green sea turtle (Chelonia mydas) Moorea.jpg', 'File:Total internal reflection of Chelonia mydas.jpg', 'File:Hawaii turtle 2.JPG', 'File:Green Sea Turtle grazing seagrass.jpg'], only: true },
  'buaya': { w: ['Saltwater_crocodile'], img: ['File:SaltwaterCrocodile(\'Maximo\').jpg', 'File:Hatchling saltwater crocodile.jpg', 'File:Saltwater crocodile (Crocodylus porosus) juvenile Rock Islands.jpg', 'File:Saltwater Crocodile (Crocodylus porosus) juvenile (8067785958).jpg', 'File:Saltwater crocodile (Crocodylus porosus), Gembira Loka Zoo, 2015-03-15 01.jpg'], only: true },
  'komodo': { w: ['Komodo_dragon'], img: ['File:202306 Varanus komodoensis.jpg', 'File:Varanus komodoensis, Komodo Island, Indonesia, 20250822 1331 2802 (cropped).jpg', 'File:Komodo Dragon, Komodo, 2016 (07) (cropped).jpg', 'File:Yuli Seperi Komodo TNKomodo-2 (cropped).jpg'], only: true },
  'anoa': { w: ['Lowland_anoa'], img: ['File:Anoa Bubalus depressicornis Surabaya Zoo.jpg', 'File:Lowland Anoa.JPG'], only: true },
  'jalak-bali': { w: ['Bali_myna'], img: ['File:Bali Myna 0A2A9443.jpg', 'File:Bali Starling - Bali Barat MG 8974 (29654702785).jpg', 'File:A Bali Starling or Rothschild Mynah at the Waddesdon Aviary.jpg', 'File:Balispreeuw (802328533).jpg', 'File:Bali Mynah.jpg'], only: true },
  'orangutan': { w: ['Bornean_orangutan'], img: ['File:Tanjung Puting30477.jpg', 'File:Orangutan Kalimantan.jpg', 'File:Bornean orangutan (Pongo pygmaeus), Tanjung Putting National Park 14.jpg'], only: true },
  'harimau-sumatra': { w: ['Sumatran_tiger'], img: ['File:Sumatran Tiger Berlin Tierpark.jpg', 'File:Sumatran tiger (11931767735).jpg', 'File:Beautiful Sumatran Tiger Cub (9711349588).jpg', 'File:Male Sumatran Tiger.jpg'], only: true },
  'badak-jawa': { w: ['Javan_rhinoceros'], img: ['File:Rhinoceros sondaicus in London Zoo.jpg', 'File:Javan Rhino 1900.jpg'], only: true },
  'cenderawasih': { w: ['Greater_bird-of-paradise'], img: ['File:Paradisaea apoda -Bali Bird Park-5.jpg', 'File:A monograph of the Paradiseidae or birds of paradise (Plate II) BHL44792765.jpg', 'File:Paradisaea apoda -Bali Bird Park-7.jpg'], only: true },
  'maleo': { w: ['Maleo'], img: ['File:Macrocephalon maleo - Muara Pusian (2).JPG', 'File:Stavenn Maleo.jpg', 'File:Macrocephalon maleo 241914820.jpg', 'File:Macrocephalon maleo 107895058.jpg', 'File:Macrocephalon maleo 241794133.jpg'], only: true },
  'tarsius': { w: ['Spectral_tarsier'], img: ['File:Tarsius tarsier Tandurusa zoo.JPG', 'File:Tarsius fuscus.jpg', 'File:Tarsius tarsier 128760822.jpg', 'File:Spectral Tarsier.jpg'], only: true },
  'gajah-sumatra': { w: ['Sumatran_elephant'], img: ['File:Elephant Sumatra ProfilG.jpg', 'File:Bayi gajah Sumatera di Taman Nasional Tesso Nilo.jpg'], only: true },
  'bintang-laut': { w: ['Protoreaster_linckii'], img: ['File:Estrella de mar de espinas rojas (Protoreaster linckii), Zanzíbar, Tanzania, 2024-06-01, DD 06.jpg', 'File:Starfish in Mombassa.JPG', 'File:Asteroidea 01.jpg'], only: true },
  'spons-porifera': { w: ['Sponge'], img: ['File:Sponges in Caribbean Sea, Cayman Islands.jpg', 'File:Aplysina archeri (Stove-pipe Sponge-pink variation).jpg'], only: true },
  'ubur-ubur': { w: ['Aurelia_aurita'], img: ['File:Aurelia aurita (Cnidaria) Luc Viatour.jpg', 'File:Moon jellyfish at Gota Sagher.JPG', 'File:Moon jellyfish in Rågårdsdal 4.jpg', 'File:Aurelia aurita (aka).jpg'], only: true },
  'cacing-tanah': { w: ['Lumbricus_terrestris'], img: ['File:Regenwurm1.jpg', 'File:Earthworm head.svg'], only: true },
  'bekicot': { w: ['Achatina_fulica'], img: ['File:Snail in Ubud, Bali, 2010 (1).jpg', 'File:Achatina fulica shell 5.png', 'File:Two achatinas.jpg', 'File:Achatina fulica shell 6.png'], only: true },
  'cumi-cumi': { w: ['Bigfin_reef_squid'], img: ['File:Calamar de arrecifes (Sepioteuthis lessoniana), Nosy Iranja, Madagascar, 2025-09-17, DD 134.jpg', 'File:Calamar de arrecifes (Sepioteuthis lessoniana), Nosy Iranja, Madagascar, 2025-09-17, DD 136.jpg', 'File:Squid komodo.jpg', 'File:Bigfin Reef Squid 2.jpg'], only: true },
  'kerang': { w: ['Tridacna'], img: ['File:Giant clam (Tridacna gigas) Michaelmas Cay.jpg', 'File:Tridacna crocea recorte.jpg', 'File:Tridacna derasa.001 - Aquarium Finisterrae.JPG', 'File:Tridacna gigas.jpg', 'File:Tridacna maxima Thiladhoo.JPG'], only: true },
  'kepiting': { w: ['Scylla_serrata'], img: ['File:CSIRO ScienceImage 10696 Mud crabs are caught measured tagged and released as part of the research into the effectiveness of green zones in Moreton Bay.jpg', 'File:Scylla serrata by OpenCage.jpg', 'File:Scylla serrata Mud Crab.jpg'], only: true },
  'laba-laba': { w: ['Nephila_pilipes'], img: ['File:Golden orb-weavers (Nephila pilipes) female and male Double Haven.jpg', 'File:Nephila pilipes, 22-10-33.jpg', 'File:Nephila pilipes 02.jpg', 'File:Nephila pilipes 3.jpg', 'File:Nephila pilipes 01.jpg'], only: true },
  'semut': { w: ['Oecophylla_smaragdina'], img: ['File:Oecophylla smaragdina - weaver ants form a bridge with their bodies in Don Det Laos.jpg', 'File:Weaverantnest05268.jpg', 'File:Oecophylla smaragdina (10.3897-zookeys.978.55767) Figure 38.jpg'], only: true },
  'lebah': { w: ['Western_honey_bee'], img: ['File:Apis mellifera Western honey bee.jpg', 'File:Bee on Lavender Blossom 2.jpg'], only: true },
  'belalang': { w: ['Valanga_nigricornis'], img: ['File:Malaysian Locust (Valanga nigricornis) (23220865943).jpg', 'File:Female Javanese Grasshopper.png'], only: true },
  'kecoak': { w: ['American_cockroach'], img: ['File:American-cockroach.jpg', 'File:Periplaneta americana - Amerikanische Großschabe 1.jpg'], only: true },
  'capung': { w: ['Crocothemis_servilia'], img: ['File:Crocothemis servilia male by kadavoor.jpg', 'File:Scarlet skimmer (Crocothemis servilia) male Pak Long.jpg', 'File:Crocothemis servilia female by kadavoor.jpg', 'File:Ruddy marsh skimmer (Crocothemis servilia) subadult male in flight.jpg'], only: true },
  'nyamuk-aedes': { w: ['Aedes_aegypti'], img: ['File:Aedes aegypti CDC-Gathany.jpg', 'File:Aedes aegypti E-A-Goeldi 1905.jpg'], only: true },
  'lalat': { w: ['Housefly'], img: ['File:Common house fly, Musca domestica.jpg', 'File:Pfurtscheller Table 31.png'], only: true },
  'daur-kupu-kupu-set': { w: ['Papilio_demoleus', 'Holometabolism'], img: ['File:Papilio demoleus 1600X1200.jpg', 'File:Common Lime Butterfly Papilio demoleus by Kadavoor.JPG'], only: true },
  'kupu-kupu': { w: ['Papilio_demoleus'], img: ['File:Common Lime Butterfly Papilio demoleus by Kadavoor.JPG', 'File:Lime Butterfly on Flower.JPG', 'File:Papilio demoleus ALT by kadavoor.jpg'], only: true },
  'ulat': { w: ['Papilio_demoleus', 'Caterpillar'], img: ['File:Papilio demoleus - Lime butterfly life cycle caterpillar at Peravoor (2).jpg', 'File:Papilio demoleus 1600X1200.jpg', 'File:Papilio demoleus (citrus swallowtail) 3rd instar larva (Bukidnon, Philippines) 04.jpg'], only: true },
  'kepompong': { w: ['Pupa', 'Papilio_demoleus'], img: ['File:Pupa of Papilio demoleus Linnaeus, 1758 - Lime Swallowtail WLB DSC 4538a.jpg', 'File:Papilio demoleus 1600X1200.jpg', 'File:無尾鳳蝶 Papilio demoleus - panoramio (2).jpg'], only: true },
  'daur-katak-set': { w: ['Tadpole', 'Frog'], img: ['File:RanaTemporariaLarva2.jpg', 'File:Tadpoles 10 days.jpg', 'File:Bufo metamorphosis.jpg', 'File:Anatomy WoodFrog.png'], only: true },
  'daur-nyamuk-set': { w: ['Mosquito', 'Aedes_aegypti'], img: ['File:Culex mosquito life cycle ta.png', 'File:Aedes aegypti E-A-Goeldi 1905.jpg', 'File:Mosquito egg SEM.jpg'], only: true },
  'daur-kecoak-set': { w: ['Cockroach', 'Hemimetabolism'], img: ['File:Cockroach nymph australia.jpg', 'File:Cockroach egglaying 1.jpg', 'File:Old Ootheca.jpg'], only: true },
  'tanaman-jagung': { w: ['Maize'], img: ['File:Zea mays - Köhler–s Medizinal-Pflanzen-283.jpg', 'File:Corntassel 7095.jpg', 'File:Cornsilk 7091.jpg', 'File:GreenCorn.JPG'], only: true },
  'tanaman-kacang': { w: ['Peanut', 'Root_nodule'], img: ['File:Arachis hypogaea - Köhler–s Medizinal-Pflanzen-163.jpg', 'File:Plante d\'arachide.jpg', 'File:Ground Nut flower (cropped).jpg', 'File:Developing pods of Peanut.jpg', 'File:Peanuts (Arachis hypogaea) - in shell, shell cracked open, shelled, peeled.jpg'], only: true },
  'biji-mono-dikotil-set': { w: ['Cotyledon', 'Monocotyledon'], img: ['File:Comparison of Monocotyledons and Dicotyledons.png', 'File:Monocot vs dicot crop Pengo.jpg', 'File:Peanut cotyledons.jpg'], only: true },
  'daun-sejajar-menyirip-menjari-set': { w: ['Leaf'], img: ['File:Fifteen plant leaves with different types of venation, stalk Wellcome V0044556.jpg', 'File:Lisc lipy.jpg'], only: true },
  'lumut': { w: ['Polytrichum'], img: ['File:Polytrichum strictum.jpeg', 'File:Polytrichum formosum anatomy en.svg'], only: true },
  'paku': { w: ['Nephrolepis', 'Sorus'], img: ['File:Nephrolepis exaltata indoor0705c.jpg', 'File:Сорус папоротника Polypodium aureum.jpg', 'File:Scattered-sori.jpg', 'File:Linear sori.jpg'], only: true },
  'pinus-konus': { w: ['Conifer_cone', 'Pine'], img: ['File:Pinus coulteri MHNT Cone.jpg', 'File:Pinus sylvestris female strobilus and cone en.svg', 'File:Young Pine Cone Center.jpg'], only: true },
  'bunga-sepatu': { w: ['Hibiscus_rosa-sinensis'], img: ['File:Hibiscus Brilliant.jpg', 'File:Hibiscus rosa-sinensis bud captured at noon in West Bengal.jpg', 'File:Hibiscus Kerala.jpg'], only: true },
  'bunga-penampang': { w: ['Flower', 'Prunus_persica'], img: ['File:Prunus cerasifera (subsp. cerasifera) sl23.jpg', 'File:Prunus cerasifera (subsp. cerasifera) sl24.jpg', 'File:Hegi Rosaceaereceptacles.png'], only: true },
  'akar-tunggang-serabut-set': { w: ['Taproot', 'Fibrous_root_system', 'Root'], img: ['File:Erbsen (Pisum sativum) im Rhizotron-14-Tage nach der Saat-Josef Schlaghecken.jpg', 'File:Buckeye6.jpg', 'File:Plant taproots.jpg', 'File:Dandelion Blackwell 0136.jpg'], only: true },
  'kentang-bertunas': { w: ['Potato'], img: ['File:Potato with sprouts.jpg', 'File:Russet potato cultivar with sprouts.jpg'], only: true },
  'bawang-merah': { w: ['Shallot', 'Bulb'], img: ['File:Shallots - sliced and whole.jpg', 'File:Shallot (Sambar Onion) (1).JPG'], only: true },
  'jahe-rimpang': { w: ['Ginger', 'Rhizome'], img: ['File:Koeh-146-no text.jpg', 'File:Ginger Root (179871501).jpeg', 'File:Ginger rhizome.jpg'], only: true },
  'stroberi-geragih': { w: ['Stolon', 'Strawberry'], img: ['File:Fragaria virginiana 15-p.bot-fraga.virgin-08.jpg', 'File:FragariaIturupensis.jpg', 'File:Britannica Wild Strawberry.png', 'File:Whole wild strawberry plant UK 2006.JPG'], only: true },
  'cocor-bebek': { w: ['Kalanchoe_pinnata'], img: ['File:Vegetative Propagation in Bryophyllum leaf.jpg', 'File:Kalanchoe pinnata Blanco1.147.png', 'File:Kalanchoe-pinnata veg reprod.jpg'], only: true },
  'singkong-stek': { w: ['Cassava', 'Cutting_(plant)'], img: ['File:Cassava stem cuttings 01.jpg', 'File:Manihot esculenta - Köhler–s Medizinal-Pflanzen-090.jpg', 'File:Cassava1 (3945716612).jpg'], only: true },
  'kaktus': { w: ['Echinopsis', 'Xerophyte'], img: ['File:Echinopsis unidentified.jpg', 'File:Echinopsis oxygona13213404.jpg'], only: true },
  'teratai': { w: ['Nymphaea_pubescens', 'Nymphaea', 'Aquatic_plant'], img: ['File:Nymphaea pubescens JNTBGRI.jpg', 'File:Nymphaea pubescens-3-JNTBGRI-kerala-India.jpg', 'File:Nymphaea alba2006-07-06.jpg'], only: true },
  'eceng-gondok': { w: ['Pontederia_crassipes'], img: ['File:Eichhornia crassipes C.jpg', 'File:Water hyacinth.jpg', 'File:IMG 2365.jpg'], only: true },
  'bakau': { w: ['Rhizophora', 'Mangrove'], img: ['File:(Rhizophora in New Caledonia) - DPLA - e8dbeca3697a8622cd3a4851f58d9fdf.jpg', 'File:Rhizophora mangle.jpg', 'File:Rhizophora mucronata with propagule at Muzhappilangad.jpg', 'File:Rhizophora mangle-propagules.jpg', 'File:Rhizophora racemosa-propagule.jpg'], only: true },
  'kantong-semar': { w: ['Nepenthes'], img: ['File:N.macrophylla x lowii.jpg', 'File:Nepenthes rafflesiana ant.jpg', 'File:Nepenthes macfarlanei upper pitcher.jpg', 'File:Nepenthes macfarlanei lower pitcher.jpg'], only: true },
  'putri-malu': { w: ['Mimosa_pudica'], img: ['File:Mimosa pudica in September month.jpg', 'File:Sensitive plant (21332).jpg', 'File:Mimosa pudica open.JPG', 'File:Mimosa pudica closed.JPG'], only: true },
  'anggrek-bulan': { w: ['Phalaenopsis_amabilis'], img: ['File:Phalaenopsis amabilis Orchi 198.jpg', 'File:Phalaenopsis amabilis Orchi 03.jpg', 'File:Phalaenopsis amabilis Orchi 004.jpg'], only: true },
  'rafflesia': { w: ['Rafflesia_arnoldii'], img: ['File:Rafflesia arnoldii, Sumatra.jpg', 'File:Rafflesia arnoldii and buds.JPG'], only: true },
  'bunga-bangkai': { w: ['Amorphophallus_titanum'], img: ['File:Amorphophallus titanum (corpse flower) - 2.jpg', 'File:Amorphophallus titanum at Meise Botanic Garden in 2024.jpg'], only: true },
  'benalu': { w: ['Dendrophthoe_pentandra', 'Mistletoe'], img: ['File:Dendrophthoe glabrescens.jpg', 'File:"+arya+" Dendrophthoe pentandra - benalu tumbuhan - ꦧꦼꦤꦭꦸ ꦠꦸꦮꦸꦲꦤ꧀ pilang kramat 2019 0.jpg'], only: true },
  'lichen': { w: ['Lichen'], img: ['File:Letharia vulpina JHollinger crop.jpg', 'File:Lichen A 13.jpg', 'File:Lichen foliacé2..JPG'], only: true },
  'ikan-badut-anemon': { w: ['Ocellaris_clownfish', 'Heteractis_magnifica'], img: ['File:Clown fish in the Andaman Coral Reef.jpg', 'File:Amphiprion ocellaris (Clown anemonefish) Nemo.jpg', 'File:Anemone purple anemonefish.jpg'], only: true },
  'kerbau-jalak': { w: ['Water_buffalo', 'Javan_myna'], img: ['File:Water buffalo at Rinca.jpg', 'File:Jungle Mynas- Looking for insects on a buffalo\'s back with a Black Drongo I Picture 278.jpg', 'File:Bank Myna (43771849272).jpg', 'File:Bank Myna (43771852052).jpg'], only: true },
  'jamur-tiram': { w: ['Pleurotus_ostreatus'], img: ['File:Pleurotus ostreatus JPG7.jpg', 'File:2025-10-26 D500-1200 Achim-Lammerts Pleurotus-ostreatus.jpg', 'File:Pleurotus ostreatus, (26156491568).jpg', 'File:Gilled mushroom cluster 2011-12-27 02.jpg'], only: true },
  'jamur-rhizopus': { w: ['Rhizopus', 'Tempeh'], img: ['File:Structure of Rhizopus spp.-english.JPG', 'File:Phycomyces.JPG'], only: true },
  'sel-ragi': { w: ['Saccharomyces_cerevisiae', 'Budding'], img: ['File:Saccharomyces cerevisiae SEM.jpg', 'File:Shmoos s cerevisiae.jpg', 'File:S cerevisiae under DIC microscopy.jpg'], only: true },
  'bakteri-bentuk-set': { w: ['Bacterial_cellular_morphologies', 'Prokaryote'], img: ['File:Bacterial morphology diagram.svg', 'File:Staphylococcus aureus Gram.jpg', 'File:ARS Campylobacter jejuni.jpg'], only: true },
  'amoeba': { w: ['Amoeba_proteus'], img: ['File:Amoeba proteus with many pseudopodia.jpg', 'File:Amoeba proteus locomotive form.jpg', 'File:Строение амебы Mayorella sp.jpg'], only: true },
  'paramecium': { w: ['Paramecium_caudatum', 'Paramecium'], img: ['File:Paramecium caudatum Ehrenberg, 1833.jpg', 'File:Paramecium caudatum.jpg', 'File:Инфузория туфелька 7.webm'], only: true },
  'euglena': { w: ['Euglena_viridis', 'Euglena'], img: ['File:Ehrenberg euglena viridis.jpg', 'File:Euglena mutabilis.ogv'], only: true },
  'virus-bakteriofag': { w: ['Escherichia_virus_T4', 'Bacteriophage'], img: ['File:Bacteriophage structure.es.png', 'File:Tevenphage.svg'], only: true },
  'sel-hewan': { w: ['Cell_(biology)', 'Eukaryote'], img: ['File:Typical human cell.tif', 'File:Celltypes.svg'], only: true },
  'sel-tumbuhan': { w: ['Plant_cell'], img: ['File:Plant cell structure-en.svg', 'File:Plant cell types.svg'], only: true },
  'kloroplas': { w: ['Chloroplast', 'Thylakoid'], img: ['File:Chloroplast II (cropped).svg', 'File:Plagiomnium affine laminazellen.jpeg', 'File:Features of a chloroplast (unannotated).jpg'], only: true },
  'penampang-daun': { w: ['Leaf', 'Mesophyll_tissue'], img: ['File:Cross section of leaf.png', 'File:Bifacial leaf cross section.jpg'], only: true },
  'stomata': { w: ['Stoma', 'Guard_cell'], img: ['File:Tomato leaf stomate 1-color.jpg', 'File:Stoma with Accompanying Guard Cells.jpg'], only: true },
  'hydrilla-ingenhousz': { w: ['Jan_Ingenhousz', 'Hydrilla'], img: ['File:Hydrilla USGS.jpg', 'File:Plant - Hydrilla verticillata - Batu kawa.jpg'], only: true },
  'tempe-tape-set': { w: ['Tempeh', 'Tapai'], img: ['File:Tempeh (8681605421).jpg', 'File:Tapai Singkong.jpg'], only: true },

  // ================= IPA 02 =================
  'sistem-pencernaan': { w: ['Human_digestive_system', 'Gastrointestinal_tract'], img: ['File:Digestive system diagram en.svg', 'File:GI normal.jpg', 'File:Digestive system diagram mn.png'], only: true },
  'gigi-jenis-set': { w: ['Human_tooth', 'Incisor', 'Canine_tooth', 'Premolar', 'Molar_(tooth)'], img: ['File:Blausen 0863 ToothAnatomy 02.png', 'File:3D Medical Animation Still Showing Types of Teeth.jpg'], only: true },
  'gigi-penampang': { w: ['Human_tooth', 'Dental_pulp', 'Tooth_enamel'], img: ['File:Blausen 0863 ToothAnatomy 02.png', 'File:Cross sections of teeth labels.png', 'File:What is Inside Human Tooth (Macro-Anatomy).jpg', 'File:Basic anatomy tooth.jpg'], only: true },
  'lidah': { w: ['Tongue', 'Lingual_papillae', 'Taste_bud'], img: ['File:زبان tongue.jpg', 'File:Tongue.agr.jpg', 'File:Spots on the tongue.jpg'], only: true },
  'lambung': { w: ['Stomach', 'Gastric_folds'], img: ['File:Gray1046.svg', 'File:Gray532.png', 'File:3D Medical Animation Stomach Structure.jpg'], only: true },
  'hati-empedu': { w: ['Liver', 'Gallbladder'], img: ['File:Anatomy Abdomen Tiesworks.jpg', 'File:3D Medical Animation liver parts.jpg', 'File:Liver veins.jpg'], only: true },
  'pankreas': { w: ['Pancreas', 'Pancreatic_islets'], img: ['File:Blausen 0699 PancreasAnatomy2.png', 'File:Gray1102.png', 'File:Sobo 1906 393.png'], only: true },
  'usus-halus-besar': { w: ['Small_intestine', 'Large_intestine', 'Appendix_(anatomy)'], img: ['File:Tractus intestinalis intestinum tenue.svg', 'File:Sobo 1906 408.png', 'File:Illu intestine-es.png', 'File:"Anatomy, physiology and laws of health;" (1885) (14779265374).jpg'], only: true },
  'vili-usus': { w: ['Intestinal_villus'], img: ['File:Small intestine low mag.jpg', 'File:Gray1059.png', 'File:MCT Chicken jejunum oblique.jpg'], only: true },
  'sistem-pernapasan': { w: ['Respiratory_system', 'Trachea', 'Bronchus'], img: ['File:Respiratory system complete en.svg', 'File:Poumons2.jpg', 'File:Illu quiz lung05.jpg'], only: true },
  'paru-paru': { w: ['Lung'], img: ['File:Lungs diagram detailed.svg', 'File:Gray973.png', 'File:Gray972.png'], only: true },
  'alveolus': { w: ['Pulmonary_alveolus', 'Gas_exchange'], img: ['File:Alveolus diagram.svg', 'File:Pulmonary Blood Circulation.png', 'File:Bronchial anatomy with description.png'], only: true },
  'insang-ikan': { w: ['Fish_gill', 'Gill'], img: ['File:Fish gill respiration.jpg', 'File:Fish gill structure.jpg', 'File:Tuna Gills in Situ 01.jpg'], only: true },
  'jantung': { w: ['Heart', 'Coronary_circulation'], img: ['File:Heart anterior exterior view.png', 'File:Heart anterior exterior view.jpg', 'File:Human heart diagram from Outlines of Human Physiology; Designed for the Use of the Higher Classes in Common Schools (1834) (14803245943).jpg'], only: true },
  'jantung-penampang': { w: ['Heart', 'Heart_valve', 'Ventricle_(heart)', 'Atrium_(heart)'], img: ['File:Heart front view he.jpg', 'File:CoraçãoFrontalPY5aal.png', 'File:2010 Chordae Tendinae Papillary Muscles.jpg'], only: true },
  'pembuluh-darah-set': { w: ['Blood_vessel', 'Artery', 'Vein', 'Capillary'], img: ['File:Blood vessels (retouched) -en.svg', 'File:Artery.svg', 'File:Blausen 0055 ArteryWallStructure.png'], only: true },
  'sel-darah-set': { w: ['Blood_cell', 'Red_blood_cell', 'White_blood_cell', 'Platelet'], img: ['File:Red blood cells.svg', 'File:Red White Blood cells.jpg', 'File:Blausen 0761 RedBloodCells.png'], only: true },
  'sistem-urinaria': { w: ['Urinary_system', 'Kidney', 'Urinary_bladder'], img: ['File:Urinary system.svg', 'File:Urinary System (Male).png'], only: true },
  'ginjal-penampang': { w: ['Kidney', 'Renal_medulla', 'Renal_cortex'], img: ['File:Blausen 0592 KidneyAnatomy 01.png'], only: true },
  'nefron': { w: ['Nephron', 'Glomerulus_(kidney)'], img: ['File:Kidney Nephron.svg', 'File:Gray1129.png', 'File:Gray1130.svg', 'File:Glomerular Physiology.png'], only: true },
  'kulit-penampang': { w: ['Human_skin', 'Sweat_gland', 'Hair_follicle'], img: ['File:Skin layers.svg', 'File:Human skin structure.svg'], only: true },
  'otak': { w: ['Human_brain', 'Lobes_of_the_brain', 'Cerebellum'], img: ['File:Brain autopsy lateral view.jpg', 'File:Skull and brain normal human.svg', 'File:Brain lobes - lateral surface.png', 'File:Brain lobes - lateral surface2.png'], only: true },
  'neuron': { w: ['Neuron', 'Myelin', 'Node_of_Ranvier'], img: ['File:Blausen 0657 MultipolarNeuron.png', 'File:Complete neuron cell diagram en.svg'], only: true },
  'mata': { w: ['Human_eye', 'Extraocular_muscles'], img: ['File:Human eye with blood vessels.jpg', 'File:Eye orbit anterior.jpg', 'File:Eye orbit anatomy anterior2.jpg'], only: true },
  'mata-penampang': { w: ['Human_eye', 'Retina', 'Fovea_centralis'], img: ['File:Schematic diagram of the human eye he.png', 'File:Schematic diagram of the human eye en-edit.png', 'File:Schematic diagram of the human eye.PNG'], only: true },
  'telinga': { w: ['Ear', 'Ossicles', 'Cochlea'], img: ['File:Human right ear (cropped).jpg', 'File:Ivory model of a human ear, Europe, 1701-1800 Wellcome L0057746.jpg', 'File:Elements of animal physiology, chiefly human (1873) (14759846346).jpg', 'File:The cat - an introduction to the study of backboned animals, especially mammals (1881) (20586784365).jpg'], only: true },
  'hidung-penampang': { w: ['Nasal_cavity', 'Nasal_concha', 'Olfactory_epithelium'], img: ['File:Anatomy of the human nasal cavity.png', 'File:Gray859.png'], only: true },
  'kerangka-manusia': { w: ['Human_skeleton'], img: ['File:Human-Skeleton.jpg', 'File:Vesalius Fabrica p163.jpg'], only: true },
  'tengkorak': { w: ['Skull'], img: ['File:Human skull - anterior view.png', 'File:Anterior nasal spine of maxilla - skull - anterior view.png', 'File:Head skull anterior view glabela.jpg', 'File:Anterior nasal spine of maxilla - skull - lateral view with circle.png'], only: true },
  'tulang-belakang': { w: ['Vertebral_column', 'Intervertebral_disc'], img: ['File:Illu vertebral column.svg', 'File:Gray 111 - Vertebral column-coloured labels.png', 'File:Gray 111 - Vertebral column-coloured.png'], only: true },
  'tulang-rusuk': { w: ['Rib_cage', 'Rib', 'Sternum'], img: ['File:Costillas.png', 'File:Gray115.png', 'File:Ribs labeled.png'], only: true },
  'tulang-paha-penampang': { w: ['Femur', 'Bone_marrow', 'Long_bone'], img: ['File:Human femur.stl', 'File:Anatomy, physiology and hygiene (1900) (14775861451).jpg'], only: true },
  'sendi-set': { w: ['Synovial_joint', 'Ball-and-socket_joint', 'Hinge_joint', 'Pivot_joint', 'Saddle_joint'], img: ['File:907 Synovial Joints.jpg', 'File:909 Types of Synovial Joints.jpg', 'File:903 Multiaxial Joint.jpg', 'File:Gray327.png'], only: true },
  'otot-lengan': { w: ['Biceps', 'Triceps', 'Antagonistic_muscles'], img: ['File:1120 Muscles that Move the Forearm Humerus Flex Sin.png', 'File:Flexión del brazo.png', 'File:Biceps brachii muscle06.png'], only: true },
  'jenis-otot-set': { w: ['Muscle_tissue', 'Skeletal_muscle', 'Smooth_muscle', 'Cardiac_muscle'], img: ['File:Types of muscle.webp', 'File:414 Skeletal Smooth Cardiac.jpg'], only: true },
  'reproduksi-wanita': { w: ['Female_reproductive_system', 'Uterus', 'Ovary', 'Fallopian_tube'], img: ['File:Female reproductive system lateral 1.png', 'File:Scheme female reproductive system-en.svg'], only: true },
  'reproduksi-pria': { w: ['Male_reproductive_system', 'Testicle', 'Vas_deferens'], img: ['File:Male anatomy 1.png', 'File:Male genital system - Front view.svg'], only: true },
  'sperma-ovum': { w: ['Egg_cell', 'Spermatozoon', 'Fertilisation'], img: ['File:Gray3.png', 'File:Human egg cell.svg', 'File:Sperm-egg.jpg', 'File:Acrosome reaction diagram.svg'], only: true },
  'janin-rahim': { w: ['Fetus', 'Placenta', 'Umbilical_cord'], img: ['File:Views of a Foetus in the Womb detail.jpg', 'File:Maternity and child care (1920) (14593999138).jpg'], only: true },
  'isi-piringku': { w: ['Healthy_diet', 'MyPlate'], x: [['Pedoman Gizi Seimbang — Kemenkes RI (Isi Piringku)', 'https://ayosehat.kemkes.go.id/isi-piringku']], img: ['File:Good Food Display - NCI Visuals Online.jpg', 'File:DFC 0804 A plate of steamed white rice topped with a runny fried egg served alongside stir-fried minced chicken with basil and sliced cucumber.jpg'], only: true },
  'sumber-karbohidrat-set': { w: ['Carbohydrate', 'Staple_food'], img: ['File:GrainProducts.jpg', 'File:Manihot esculenta dsc07325.jpg'], only: true },
  'sumber-protein-set': { w: ['Protein_(nutrient)'], img: ['File:Pesce al mercato 1.JPG', 'File:MungBean.jpg', 'File:Tempeh tempe.jpg', 'File:Tempeh 003.jpg'], only: true },
  'sumber-lemak-set': { w: ['Fat', 'Cooking_oil'], img: ['File:Avocado Hass - single and halved.jpg', 'File:Day 051 - Photo365 - Fresh (15973465233).jpg'], only: true },
  'sumber-vitamin-mineral-set': { w: ['Vitamin', 'Mineral_(nutrient)'], img: ['File:2023-08-25 - Halved melon - mould encroaching from one end - DSN5354-1.jpg', 'File:Carrots of many colors.jpg'], only: true },
  'virus-dengue': { w: ['Dengue_virus'], img: ['File:Aedes Mosquito and Dengue Virus Particles.jpg', 'File:SAG Dengue-Virus 160413 01.jpg'], only: true },
  'virus-corona': { w: ['SARS-CoV-2'], img: ['File:Novel Coronavirus SARS-CoV-2.jpg', 'File:SARS-CoV-2 (yellow).jpg', 'File:Coronavirus. SARS-CoV-2.png'], only: true },
  'virus-influenza': { w: ['Influenza_A_virus', 'Orthomyxoviridae'], img: ['File:Viruses-12-00504-g001.webp', 'File:Influenza A - late passage.jpg', 'File:Viruses-10-00497-g001.png'], only: true },
  'bakteri-tbc': { w: ['Mycobacterium_tuberculosis'], img: ['File:TB Culture.jpg', 'File:Mycobacterium tuberculosis MEB.jpg', 'File:Mycobacterium tuberculosis.jpg'], only: true },
  'vaksin-suntik': { w: ['Vaccine', 'Vial', 'Syringe'], img: ['File:Smallpox vaccine.jpg', 'File:Vaccine Vial (NIH BioArt 536).png'], only: true },
  'masker-medis': { w: ['Surgical_mask'], img: ['File:Surgical face mask.jpg', 'File:Внешний слой медицинской маски (поляризация).tif'], only: true },
  'alat-kebersihan-set': { w: ['Hygiene', 'Toothbrush', 'Soap'], img: ['File:Toothbrush x3 20050716 002.jpg', 'File:Toothbrush, Toothpaste, Dental Care (571741).jpg'], only: true },
  'tensimeter': { w: ['Sphygmomanometer'], img: ['File:Sphygmomanometer&Cuff.JPG', 'File:Sphygmomanometer.JPG', 'File:Clinical Mercury Manometer.jpg'], only: true },
  'glukometer': { w: ['Glucose_meter'], img: ['File:Glucose meters.jpg', 'File:Blausen 0299 Diabetes BloodGlucoseMeter.png'], only: true },
  'stetoskop': { w: ['Stethoscope'], img: ['File:Stethoscope-2.png', 'File:2023 Stetoskop.jpg', 'File:Stethoscope-ja-2019.jpg'], only: true },
  'fermentasi-produk-set': { w: ['Fermentation_in_food_processing', 'Nata_de_coco', 'Soy_sauce'], img: ['File:Sourdough starter.jpg', 'File:Natto mixed.jpg', 'File:Tempeh tempe.jpg', 'File:Tempeh 003.jpg'], only: true },

  // ================= IPA 03 =================
  'neraca-pegas': { w: ['Spring_scale', 'Newton_(unit)'], img: ['File:Weeghaak.JPG', 'File:Spring scale - 3241.jpg', 'File:Spring scale. Made in USSR.jpg', 'File:Spring balance.PNG'], only: true },
  'bola-sepak': { w: ['Ball_(association_football)'], img: ['File:1970 - Telstar (Mexico) (4171467668).jpg'], only: true },
  'plastisin': { w: ['Plasticine', 'Modelling_clay'], img: ['File:Little girl holding plasticine. (49810941302).jpg'], only: true },
  'ban-berulir': { w: ['Tread', 'Friction'], img: ['File:Schwalbe Road Cruiser black & white 47-622 bicycle tires (6).jpg', 'File:Back bicycle tyre.JPG', 'File:Mountain bike tires.JPG', 'File:Покрышка.jpg'], only: true },
  'jungkat-jungkit': { w: ['Seesaw', 'Lever'], img: ['File:Seesaw-aa.jpg', 'File:Stand-up seesaw playground Achim.jpg', 'File:Up and down.jpg'], only: true },
  'tuas-jenis-1-set': { w: ['Lever', 'Scissors', 'Pliers'], img: ['File:Pair of scissors with black handle, 2015-06-07.jpg', 'File:Small pair of blue scissors.jpg'], only: true },
  'tuas-jenis-2-set': { w: ['Lever', 'Bottle_opener', 'Nutcracker'], img: ['File:Fs beer bottle opener 20220421 144319.jpg'], only: true },
  'tuas-jenis-3-set': { w: ['Lever', 'Tweezers', 'Stapler'], img: ['File:Functional ceramic.jpg'], only: true },
  'gerobak-dorong': { w: ['Wheelbarrow'], img: ['File:Brouette Vespa.jpg', 'File:Construction of Marilao station in Ibayo SM 14.jpg'], only: true },
  'katrol-tetap': { w: ['Pulley', 'Well'], img: ['File:PulleyShip.JPG', 'File:Water Well Pulley (1).JPG', 'File:Well buckets, Ichijodani 200507.jpg'], only: true },
  'katrol-bergerak': { w: ['Pulley', 'Mechanical_advantage'], img: ['File:Polispasto2B.jpg', 'File:Pulley1a.svg'], only: true },
  'katrol-majemuk': { w: ['Block_and_tackle'], img: ['File:Pulley3a.svg', 'File:Pulley2a.svg', 'File:Tackles.png'], only: true },
  'bidang-miring-papan': { w: ['Inclined_plane'], img: ['File:Chartres, Hôtel Montescot 08 rampe PMR.jpg', 'File:Piano inclinato inv 1041 IF 21341.jpg'], only: true },
  'sekrup-baut': { w: ['Screw', 'Nut_(hardware)', 'Jack_(device)'], img: ['File:Screws.jpg', 'File:Screw Head Shapes - Combo Pan and Countersunk.jpg', 'File:Screw Head Shapes - Combo Flat and Truss.jpg', 'File:Late 1900s zinc plated M12 8 G hex head machine bolt and nut by ESKA GmbH Automotive Germany view 1.jpg'], only: true },
  'baji-set': { w: ['Wedge', 'Axe', 'Chisel'], img: ['File:Wedge-1.jpg', 'File:Felling axe.jpg', 'File:Chisel wood 24mm.jpg'], only: true },
  'tangga-rumah': { w: ['Ladder'], img: ['File:Folding ladder 1.webp', 'File:Folding ladder 2.webp'], only: true },
  'sepeda': { w: ['Bicycle', 'Bicycle_gearing'], img: ['File:Left side of Flying Pigeon.jpg', 'File:Chain lifespan.jpg', 'File:Bicycle crankset Shimano 105 R7000 (chainring 50-34, length 172.5mm, 11 speed).jpg'], only: true },
  'roda-berporos-set': { w: ['Wheel_and_axle', 'Screwdriver', 'Steering_wheel'], img: ['File:Jeweler\'s screwdriver.jpg', 'File:Magnetschraubendreher IMGP1940.jpg', 'File:Volvo steering wheel.jpg'], only: true },
  'alat-energi-listrik-panas-set': { w: ['Clothes_iron', 'Rice_cooker', 'Electric_kettle'], img: ['File:Teal and white electric steam iron - side view.jpg', 'File:Rice-cooker.jpg', 'File:Rival Rice Cooker.jpg'], only: true },
  'kipas-angin': { w: ['Mechanical_fan'], img: ['File:Hatari 18 inch fan.jpg', 'File:Electric Fan 240x355.jpg'], only: true },
  'lampu-bohlam': { w: ['Incandescent_light_bulb'], img: ['File:Gluehlampe 01 KMJ.png', 'File:Livermore Centennial Light Bulb.jpg', 'File:Carbonfilament.jpg'], only: true },
  'lampu-led-cfl-set': { w: ['LED_lamp', 'Compact_fluorescent_lamp', 'Incandescent_light_bulb'], img: ['File:Led-lampa.jpg', 'File:LEDfilamentLightBulbE27.jpg', 'File:LED lanp with CFL design.jpg'], only: true },
  'senter': { w: ['Flashlight'], img: ['File:LED Flashlights.jpg', 'File:1899 Eveready flashlight.jpg'], only: true },
  'lilin-menyala': { w: ['Candle'], img: ['File:LA2 Skultuna kontorsljusstake.jpg', 'File:Candle flame closeup.jpg'], only: true },
  'speaker-mikrofon-set': { w: ['Loudspeaker', 'Microphone'], img: ['File:Loudspeaker-bass.png', 'File:Dynamic-microphone-senn.jpg'], only: true },
  'kompor-gas': { w: ['Gas_stove'], img: ['File:Gas oven flame.jpg', 'File:Gas Stove (two burners).jpg', 'File:Gas stove blue flames.jpg'], only: true },
  'dinamo-sepeda': { w: ['Bottle_dynamo', 'Dynamo'], img: ['File:AXA HR Traction Power Control-8182.jpg', 'File:Dynamo-Anbau.png'], only: true },
  'panel-surya': { w: ['Solar_panel', 'Solar_cell'], img: ['File:Ground mounted solar panels.gk.jpg', 'File:As solar firmengebaude.jpg'], only: true },
  'kincir-angin': { w: ['Wind_turbine'], img: ['File:Windmills D1-D4 (Thornton Bank).jpg', 'File:Wind turbines along North Middle Road, Essex County, Ontario, 2025-06-29.jpg'], only: true },
  'baterai-set': { w: ['Electric_battery', 'AA_battery', 'Automotive_battery'], img: ['File:Batteries.jpg', 'File:Dry cell (PSF).png'], only: true },
  'rangkaian-seri': { w: ['Series_and_parallel_circuits'], img: ['File:Battery Series Bulb.jpg', 'File:Battery Series and Parallel Bulb.jpg'], only: true },
  'rangkaian-paralel': { w: ['Series_and_parallel_circuits'], img: ['File:Parallel circuit 2 bulbs 3 ammeters.png', 'File:Parallel circuit 2 bulbs 2 ammeters.png'], only: true },
  'sakelar-stopkontak-set': { w: ['Light_switch', 'AC_power_plugs_and_sockets', 'Circuit_breaker'], img: ['File:LightSwitch.jpg', 'File:MTR CRH380A AC power plugs and sockets 201710.jpg'], only: true },
  'kabel-penampang': { w: ['Electrical_wiring', 'Electrical_cable'], img: ['File:400 kV Underground Cable.jpg', 'File:NIE Cable.jpg'], only: true },
  'konduktor-isolator-set': { w: ['Electrical_conductor', 'Insulator_(electricity)'], img: ['File:Ceramic electric insulator.jpg', 'File:Electric guide 3×2.5 mm.jpg', 'File:Lautsprecherkabel Makro nah.jpg'], only: true },
  'magnet-bentuk-set': { w: ['Magnet', 'Horseshoe_magnet'], img: ['File:Bar magnet crop.jpg', 'File:Metal shavings around bar magnet (close-up).jpg'], only: true },
  'magnet-serbuk-besi': { w: ['Magnetic_field'], img: ['File:Magnet0873.png', 'File:Horseshoe Magnetic Filings (Flipped 180).jpg', 'File:Bar-magnet-iron-filings max.jpg'], only: true },
  'kompas': { w: ['Compass'], img: ['File:2016 Busola.JPG', 'File:Walkers compass arp.jpg'], only: true },
  'elektromagnet': { w: ['Electromagnet'], img: ['File:Electromagnet-with-9V-battery.jpg', 'File:AGEM5520.jpg'], only: true },
  'bel-listrik': { w: ['Electric_bell'], img: ['File:DoorBell 001.jpg', 'File:Block Instruments-2.JPG', 'File:Polarised electric bell (Rankin Kennedy, Electrical Installations, Vol V, 1903).jpg'], only: true },
  'tekanan-hidrostatis-botol': { w: ['Hydrostatics', 'Torricelli%27s_law'], img: [], only: true },
  'tekanan-benda-padat-set': { w: ['Pressure', 'Snowshoe', 'Drawing_pin'], img: ['File:Pin for a pinboard 2013 PD.jpg', 'File:Red pushpin on stack of dimensional cards.jpg'], only: true },
  'elektroskop': { w: ['Electroscope'], img: ['File:Gold leaf electroscope with ground strips.png', 'File:Gold leaf electroscope homemade.jpg', 'File:Opfindelsernes bog3 fig282.png'], only: true },
  'balon-listrik-statis': { w: ['Static_electricity', 'Triboelectric_effect'], img: ['File:Attractive-electric-force-between-hair-and-balloon.jpg', 'File:Repulsive-electric-force-between-balloons.jpg', 'File:Balloons (static electricity).png'], only: true },
  'transformator': { w: ['Transformer'], img: ['File:Philips N4422 - power supply transformer-2098.jpg', 'File:Transformer3d col3.svg'], only: true },
  'galvanometer-kumparan': { w: ['Electromagnetic_induction', 'Galvanometer'], img: ['File:Induction experiment.png', 'File:A moving coil galvanometer. Wellcome M0016397.jpg'], only: true },

  // ================= IPA 04 =================
  'cermin-datar': { w: ['Mirror', 'Plane_mirror'], img: ['File:Mirror.jpg', 'File:Enhanced aluminum coated first surface mirror on an optical flat.JPG'], only: true },
  'cermin-cekung-cembung-set': { w: ['Curved_mirror'], img: ['File:2008-03-14 Convex mirror in Atlanta garage entrance.jpg', 'File:UserRedCoat.JPG', 'File:Concave Mirror Diagram.png'], only: true },
  'cermin-cembung-jalan': { w: ['Traffic_mirror', 'Curved_mirror'], img: ['File:2008-03-14 Convex mirror in Atlanta garage entrance.jpg', 'File:Astley Lodge reflected in a convex road safety mirror - geograph.org.uk - 6913531.jpg', 'File:Convex traffic mirror by a bend at Ford - geograph.org.uk - 6059314.jpg'], only: true },
  'lensa-cembung-cekung-set': { w: ['Lens'], img: ['File:Lenses en.svg', 'File:Lens1.svg'], only: true },
  'lup': { w: ['Magnifying_glass'], img: ['File:Mag glass request.jpg', 'File:BelOMO 10× achromatic triplet loupe 2.jpg'], only: true },
  'kacamata-minus-plus-set': { w: ['Glasses', 'Corrective_lens', 'Near-sightedness'], img: ['File:2023 Okulary korekcyjne.jpg'], only: true },
  'prisma-kaca': { w: ['Dispersive_prism', 'Prism_(optics)'], img: ['File:Light dispersion of a mercury-vapor lamp with a flint glass prism IPNr°0125.jpg', 'File:Dispersive prism.png', 'File:Comparison refraction diffraction spectra.svg'], only: true },
  'cakram-newton': { w: ['Newton_disc'], img: ['File:Disque newton.png'], only: true },
  'periskop': { w: ['Periscope'], img: ['File:Periscope simple.svg'], only: true },
  'kamera-lubang-jarum': { w: ['Pinhole_camera', 'Camera_obscura'], img: ['File:Pinhole-camera.svg'], only: true },
  'mikroskop': { w: ['Optical_microscope'], img: ['File:Dark Cool Optical Microscope.png', 'File:Compound Microscope (cropped).JPG'], only: true },
  'teropong-bintang': { w: ['Refracting_telescope'], img: ['File:Zeiss2.jpg', 'File:Kepschem.png'], only: true },
  'garpu-tala': { w: ['Tuning_fork'], img: ['File:TuningFork659Hz.jpg', 'File:Tuning fork on resonator.jpg'], only: true },
  'alat-musik-set': { w: ['Angklung', 'Suling', 'Kendang', 'Gamelan'], img: ['File:Eight-pitch Angklung, Mitchell Park, Milwaukee.jpg', 'File:Angklung-arumba.jpg', 'File:Gamelan Jawa - Kendang Ageng (2).jpg'], only: true },
  'telepon-kaleng': { w: ['Tin_can_telephone'], img: ['File:Chris Potter - 3D Tin Can Phones.jpg'], only: true },
  'termometer-set': { w: ['Thermometer', 'Medical_thermometer'], img: ['File:Mercury Thermometer.jpg', 'File:Clinical thermometer 38.7.JPG'], only: true },
  'termos-penampang': { w: ['Vacuum_flask'], img: ['File:Thermos.JPG', 'File:Vacuum Dewar Flask.svg', 'File:Gustav R. Paalen, Double Welled Vessel 1909.png'], only: true },
  'panci-pegangan': { w: ['Cookware_and_bakeware', 'Stock_pot'], img: ['File:Pot, cooking (AM 1999.44.4-1).jpg'], only: true },
  'perpindahan-panas-set': { w: ['Heat_transfer', 'Thermal_conduction', 'Convection'], img: ['File:Heat-transmittance-means2.jpg', 'File:Kochendes wasser02.jpg'], only: true },
  'wujud-zat-set': { w: ['State_of_matter'], img: ['File:Silica.svg', 'File:SiO² Quartz.svg'], only: true },
  'es-batu-mencair': { w: ['Ice_cube', 'Melting'], img: ['File:Ice cubes openphoto.jpg', 'File:Hielos.jpg'], only: true },
  'mengembun-gelas': { w: ['Condensation'], img: ['File:Drop-of-water-condensation-pattern-backgrounds-textures.jpg'], only: true },
  'kapur-barus': { w: ['Mothball', 'Naphthalene'], img: ['File:White coloured mothball (naphthalene ball) 20230315 180901.jpg', 'File:A packet of white coloured mothball (naphthalene ball) 20230315 180612.jpg'], only: true },
  'dry-ice': { w: ['Dry_ice', 'Sublimation_(phase_transition)'], img: ['File:Dry Ice 1 (cropped).jpg', 'File:Dry ice pellet subliming in water.jpg', 'File:Dry ice sublimation march 29 2021.webm'], only: true },
  'perubahan-kimia-set': { w: ['Chemical_change', 'Rust'], img: ['File:Rusted Nails.jpeg', 'File:Rusted nails and old timber (39700738992).jpg'], only: true },
  'perubahan-fisika-set': { w: ['Physical_change'], img: ['File:Melting chocolate - step 4.JPG', 'File:Melting chocolate - step 5.JPG', 'File:CardboardSet001 PREVIEW.png'], only: true },
  'filtrasi': { w: ['Filtration', 'Filter_paper'], img: ['File:Hot Filtration set up.jpg', 'File:Hot FIltration.jpg', 'File:Cold Filtration.jpg'], only: true },
  'distilasi': { w: ['Distillation', 'Liebig_condenser'], img: ['File:Retort-in-operation-early-chemistry.png', 'File:Distillation of dry and oxygen-free toluene.jpg'], only: true },
  'kromatografi': { w: ['Paper_chromatography'], img: ['File:Chromatography tank.png', 'File:T.baccata-paper chromatography.jpg'], only: true },
  'penguapan-garam': { w: ['Evaporation', 'Evaporating_dish', 'Sea_salt'], img: ['File:Abdampfschalen verschiedene Groessen.jpg'], only: true },
  'larutan-koloid-suspensi': { w: ['Solution_(chemistry)', 'Colloid', 'Suspension_(chemistry)'], img: ['File:SaltInWaterSolutionLiquid.jpg'], only: true },
  'efek-tyndall': { w: ['Tyndall_effect'], img: ['File:Koloidní povoha želatiny.jpg', 'File:Lyubertsy, A. A. Skochinsky Mining Institute - interior (16781901395).jpg'], only: true },
  'slinki': { w: ['Slinky', 'Longitudinal_wave'], img: ['File:2006-02-04 Metal spiral.jpg', 'File:Slinky rainbow.jpg'], only: true },
  'model-atom': { w: ['Bohr_model', 'Carbon'], img: ['File:Bohr atom model.svg', 'File:Blausen 0342 ElectronEnergyLevels.png'], only: true },

  // ================= IPA 05 =================
  'matahari': { w: ['Sun'], img: ['File:The Sun in white light.jpg'], only: true },
  'merkurius': { w: ['Mercury_(planet)'], img: ['File:Mercury in true color.jpg', 'File:Mercury render with Blender 01.png'], only: true },
  'venus': { w: ['Venus'], img: ['File:Venus from Mariner 10.jpg'], only: true },
  'bumi': { w: ['Earth'], img: ['File:The Blue Marble, AS17-148-22727.jpg', 'File:Earth From the Perspective of Artemis II.jpg'], only: true },
  'bulan': { w: ['Moon'], img: ['File:FullMoon2010.jpg', 'File:Near side of the moon 4k.png', 'File:Far side of the moon 4k.png'], only: true },
  'mars': { w: ['Mars'], img: ['File:Mars - August 30 2021 - Flickr - Kevin M. Gill.png'], only: true },
  'jupiter': { w: ['Jupiter'], img: ['File:Jupiter OPAL 2024.png', 'File:Jupiter size.png'], only: true },
  'saturnus': { w: ['Saturn'], img: ['File:Saturn global view from Cassini, rings open Better Colour.png'], only: true },
  'uranus': { w: ['Uranus'], img: ['File:Uranus Voyager2 color calibrated.png'], only: true },
  'neptunus': { w: ['Neptune'], img: ['File:Neptune Voyager2 color calibrated.png'], only: true },
  'tata-surya-deret': { w: ['Solar_System', 'Planet'], img: ['File:Solar System True Color EN.png'], only: true },
  'fase-bulan-deret': { w: ['Lunar_phase'], img: ['File:Moon phases en.jpg'], only: true },
  'komet': { w: ['Comet'], img: ['File:Comet Hale-Bopp 1995O1.jpg', 'File:Comet C2020F3 NEOWISE over California desert landscape.png'], only: true },
  'meteorit': { w: ['Iron_meteorite', 'Widmanst%C3%A4tten_pattern'], img: ['File:TamentitMeteorite.JPG', 'File:Iron meteorite. Toluca, Mexico-8913.jpg', 'File:Casas Grandes meteorite, pattern.jpg'], only: true },
  'bumi-lapisan': { w: ['Internal_structure_of_Earth'], img: ['File:Earth cutaway.png', 'File:Earth Internal Structure.svg'], only: true },
  'globe': { w: ['Globe', 'Axial_tilt'], img: ['File:The Great Globe, Guyot Hall, Princeton University.jpg'], only: true },
  'batuan-beku-set': { w: ['Igneous_rock', 'Granite', 'Basalt', 'Obsidian', 'Pumice'], img: ['File:Biotite Granite student sample.jpg', 'File:Hand sample from the S-type Strathbogie Granite, Australia.tif', 'File:Granite sample.JPG'], only: true },
  'batuan-sedimen-set': { w: ['Sedimentary_rock', 'Sandstone', 'Limestone', 'Conglomerate_(geology)'], img: ['File:Ferruginous Sandstone (banded) Student sample label.JPG', 'File:USDA Mineral Sandstone 93c3955.jpg', 'File:Jacobsville Sandstone sample 2.jpg'], only: true },
  'batuan-metamorf-set': { w: ['Metamorphic_rock', 'Marble', 'Slate', 'Gneiss'], img: ['File:Quartzite.jpg', 'File:Basalt-hand-sample.tif'], only: true },
  'profil-tanah': { w: ['Soil_horizon', 'Soil_profile'], img: ['File:Profil glebowy.jpg', 'File:Soil Horizons.svg', 'File:Soil Profile 20210710 Hessaraghatta Main Road.jpg'], only: true },
  'sda-tak-terbarukan-set': { w: ['Non-renewable_resource', 'Coal', 'Petroleum'], img: ['File:GoldOreUSGOV.jpg', 'File:Coal lumps.jpg'], only: true },
  'sda-terbarukan-set': { w: ['Renewable_resource', 'Lumber'], img: ['File:Komplementärkontrast (Sägewerk bei Fügen, Zillertal) - panoramio.jpg', 'File:Teak wood -cross section.jpg'], only: true },
  'alat-cuaca-set': { w: ['Weather_station', 'Barometer', 'Anemometer', 'Rain_gauge'], img: ['File:Davis VantagePro.jpg', 'File:Anemometer.jpg'], only: true },
  'sampah-organik-anorganik-set': { w: ['Biodegradable_waste', 'Waste_sorting'], img: ['File:Banane-A-05 cropped.jpg'], only: true },
  'tempat-sampah-3': { w: ['Waste_container', 'Waste_sorting'], img: ['File:Waste container in Japan.jpg'], only: true },

  // ================= IPA 06 =================
  'alat-gelas-lab-set': { w: ['Laboratory_glassware', 'Beaker_(laboratory_equipment)', 'Erlenmeyer_flask'], img: ['File:Lab glassware.jpg', 'File:Erlenmeyer and Filtering Flask.jpg', 'File:3D printed test tube rack in use.jpg'], only: true },
  'gelas-ukur': { w: ['Graduated_cylinder', 'Meniscus_(liquid)'], img: ['File:Different types of graduated cylinder- 10ml, 25ml, 50ml and 100 ml graduated cylinder.jpg', 'File:Grauduate cylinder reading.png', 'File:Graduated cylinder illustration.png'], only: true },
  'pembakar-spiritus': { w: ['Alcohol_burner', 'Tripod_(laboratory)'], img: ['File:Aluminum alcohol burner.jpg', 'File:Alcohol burner1.jpg', 'File:Laboratory tripod with other lab equipments.jpg'], only: true },
  'neraca-ohauss': { w: ['Triple_beam_balance'], img: ['File:Triple beam balance3.JPG', 'File:Triple beam balance1.JPG'], only: true },
  'stopwatch': { w: ['Stopwatch'], img: ['File:Stoppuhr digital noBG.jpg', 'File:Louis Moinet\'s "Compteur de Tierces".jpg'], only: true },
  'kaca-preparat': { w: ['Microscope_slide'], img: ['File:MicroscopeSlides.jpg', 'File:Urinary phase-contrast microscopy.jpg', 'File:Standard and large microscope slide.jpg'], only: true },

  // ================= MTK =================
  'sempoa': { w: ['Soroban', 'Abacus'], img: ['File:Soroban.JPG', 'File:Science museum 030.jpg', 'File:چرتکه ژاپنی.jpg'], only: true },
  'pizza-pecahan': { w: ['Pizza'], img: ['File:Pizza-3007395.jpg', 'File:Neapolitan pizza.jpg'], only: true },
  'cokelat-batang': { w: ['Chocolate_bar'], img: ['File:Green and Black\'s dark chocolate bar 2.jpg'], only: true },
  'kue-bolu-pecahan': { w: ['Sponge_cake', 'Layer_cake'], img: ['File:Victoria Sponges.jpg', 'File:Castella,made in nagasaki-city,japan.JPG', 'File:Sifon pandan.JPG'], only: true },
  'kelereng-kantong': { w: ['Marble_(toy)'], img: ['File:Marble collector - Flickr - smkybear.jpg'], only: true },
  'bangun-datar-set': { w: ['Polygon', 'Quadrilateral'], img: ['File:21st-century-pattern-blocks.jpg', 'File:Pattern Blocks and Deci-Blocks.jpg'], only: true },
  'tangram': { w: ['Tangram'], img: ['File:Tangram set 00.jpg', 'File:Tangram-man.svg'], only: true },
  'alat-geometri-set': { w: ['Protractor', 'Compass_(drawing_tool)', 'Set_square'], img: ['File:Grad protractor.png', 'File:Protractor Rapporteur Degrees V3.jpg', 'File:Teknor compass drawing tool.jpg'], only: true },
  'jam-analog': { w: ['Clock', 'Clock_face'], img: ['File:Pendulum clock by Jacob Kock, antique furniture photography, IMG 0931 edit.jpg', 'File:Matthew Norman carriage clock.jpg'], only: true },
  'geoboard': { w: ['Geoboard'], img: ['File:Geoboard.JPG', 'File:25 peg geoboard.JPG'], only: true },
  'benda-lingkaran-set': { w: ['Circle', 'Plate_(dishware)'], img: ['File:Circle-withsegments.svg', 'File:Obama china service dinner plate 2015.jpeg'], only: true },
  'kubus': { w: ['Cube'], img: ['File:Cube-h.svg', 'File:One-red-dice-01.jpg'], only: true },
  'balok': { w: ['Cuboid', 'Rectangular_cuboid'], img: ['File:Cuboid no label.svg', 'File:Pieces of the game KUBO.jpg'], only: true },
  'prisma-segitiga': { w: ['Triangular_prism'], img: ['File:Prism 3 (green).png', 'File:Optisch prisma.png'], only: true },
  'limas-segiempat': { w: ['Square_pyramid'], img: ['File:Square pyramid.png', 'File:All Gizah Pyramids.jpg', 'File:Square pyramid net.svg'], only: true },
  'limas-segitiga': { w: ['Tetrahedron'], img: ['File:Triangular pyramid1.png', 'File:Tetrahedron (green).png', 'File:Tetrahedron flat.svg'], only: true },
  'tabung': { w: ['Cylinder'], img: ['File:Circular cylinder rh.svg'], only: true },
  'kerucut': { w: ['Cone'], img: ['File:Cone with labeled Radius, Height, Angle and Side v2.svg', 'File:Cone 3d.png'], only: true },
  'bola': { w: ['Sphere'], img: ['File:Sphere wireframe 10deg 6r.svg', 'File:Sphere and Ball.png'], only: true },
  'bangun-ruang-set': { w: ['Solid_geometry', 'Platonic_solid'], img: ['File:Geometric solids 16th century.jpg'], only: true },
  'jaring-jaring-kubus': { w: ['Net_(polyhedron)'], img: ['File:Cube net pic.png', 'File:Net of cube.png'], only: true },
  'kubus-satuan': { w: ['Unit_cube', 'Linking_cubes'], img: ['File:Linking cm cubes 2.JPG', 'File:Sugar cubes in India 06.jpg'], only: true },
  'akuarium': { w: ['Aquarium'], img: ['File:Amaterske akvarium.jpg'], only: true },
  'benda-bangun-ruang-set': { w: ['Tumpeng', 'Tin_can', 'Ice_cream_cone'], img: ['File:Tumpeng-Jawa.jpg', 'File:Nasi Kuning dan Ungkep Ayam.jpg', 'File:Fransk Linolja - 2021.jpg'], only: true },
  'tandon-air': { w: ['Water_tank'], img: ['File:Watertank29Palms.JPG'], only: true },
  'alat-ukur-panjang-set': { w: ['Ruler', 'Tape_measure', 'Calipers'], img: ['File:CarpentersRule.png', 'File:Measuring-tape.jpg', 'File:Steel ruler closeup.jpg'], only: true },
  'timbangan-set': { w: ['Weighing_scale', 'Steelyard_balance'], img: ['File:Balance à tabac 1850.JPG', 'File:Weegschaal (unster) met 2 gewichten in brons, 50 tot 200 NC, vindplaats- Onbekend, collectie Gallo-Romeins Museum Tongeren, GRM 48.jpg', 'File:2023 Elektroniczna waga kuchenna.jpg', 'File:Weighing scale BW 2012-01-14 16-44-55 5-01 5-07.jpg'], only: true },
  'anak-timbangan': { w: ['Mass', 'Calibration_weight'], img: ['File:Poids fonte 2 kg 03 (cropped).jpg', 'File:Set of five Swedish nested cup brass weights from 1852.jpg'], only: true },
  'wadah-volume-set': { w: ['Measuring_cup', 'Measuring_spoon', 'Bucket'], img: ['File:Simple Measuring Cup.jpg', 'File:MeasuringCups2.JPG', 'File:Metric Volume Measuring Vessels Frontsides-In use.jpg'], only: true },
  'keran-debit': { w: ['Tap_(valve)'], img: ['File:Tap in Fužine castles yard.jpg', 'File:Tap-gb0fe5d2cc 1920.jpg'], only: true },
  'jam-tangan-kalender': { w: ['Watch', 'Hourglass', 'Calendar'], img: ['File:Casio OCEANUS OCW-S1350PC-1AJR 01.JPG', 'File:Wooden hourglass 3.jpg'], only: true },
  'speedometer': { w: ['Speedometer', 'Odometer'], img: ['File:Ford Mondeo MK3 ST220 - Speedometer.jpg', 'File:Ford Mondeo MK3 ST220 - Speedometer (light).jpg', 'File:Jeep Odometer.jpg'], only: true },
  'kendaraan-set': { w: ['Car', 'Motorcycle', 'Bus'], img: ['File:2005 Toyota Corolla 1.4 T3.jpg', 'File:Ktm motorcycle side view 114275 3840x2160.jpg', 'File:Motorcycle parked on the side of the street.jpg'], only: true },
  'belanja-set': { w: ['Grocery_store', 'Price_tag'], img: ['File:Shopping Trolleys (809290640) (cropped).jpg'], only: true },
  'celengan': { w: ['Piggy_bank'], img: ['File:Sparschwein Haspa02.jpg'], only: true },
  'peta-skala': { w: ['Topographic_map', 'Scale_(map)'], img: ['File:Topographic-Relief-perspective-sample.jpg', 'File:MTN50-0535-2013-cns Algete.jpg', 'File:IsraelCVFRtopography.jpg'], only: true },
  'maket-rumah': { w: ['Architectural_model'], img: ['File:Model of Chochikukyo House 2.jpg'], only: true },
  'dadu': { w: ['Dice'], img: ['File:6sided dice (cropped).jpg'], only: true },
  'koin-peluang': { w: ['Coin_flipping', 'Coin'], img: ['File:Pompey by Nasidius.jpg'], only: true },
  'spinner': { w: ['Spinner_(game)'], img: ['File:Myst board game spinner.png', 'File:Monopoly spinner.jpg'], only: true },
  'kartu-bernomor': { w: ['Playing_card', 'Ping-pong_ball'], img: ['File:AcetoFive.JPG', 'File:Playing cards modified.jpg'], only: true },
  'batang-korek-pola': { w: ['Match', 'Matchstick_puzzle'], img: ['File:Streichholz.jpg', 'File:Friction d\'une allumette.jpg'], only: true },
  'timbangan-aljabar': { w: ['Weighing_scale', 'Balance_(ability)'], img: ['File:Balance à tabac 1850.JPG'], only: true },
  'susunan-pola-bola': { w: ['Triangular_number', 'Figurate_number'], img: ['File:Illustration of Triangular Number T 4 Leading to a Rectangle (yellow-green).svg', 'File:Bead ornaments, triangular, 14 MET sf981168.jpg'], only: true },
  // ================= Tambahan (audit cakupan) =================
  'anjing': { w: ['Dog'], img: ['File:Dog - നായ-6.JPG', 'File:Blue merle koolie short coat heading sheep (cropped).jpg'], only: true },
  'kuda': { w: ['Horse'], img: ['File:Nokota Horses cropped.jpg', 'File:Horse-and-pony.jpg'], only: true },
  'tikus': { w: ['Brown_rat'], img: ['File:Brown Rat (Rattus norvegicus).jpg', 'File:Brown rat (Rattus norvegicus) Drenthe 2.jpg'], only: true },
  'burung-pipit': { w: ['Eurasian_tree_sparrow'], img: ['File:Passer montanus saturatus.JPG', 'File:Passer montanus malaccensis @ Kuala Lumpur, Malaysia (1).jpg'], only: true },
  'burung-hantu': { w: ['Barn_owl'], img: ['File:Tyto alba -England -perching on a headstone-8.jpg', 'File:Tyto alba portrait in tropical setting.jpg', 'File:Barn Owl, Lancashire.jpg'], only: true },
  'unta': { w: ['Dromedary'], img: ['File:Camelus dromedarius in Nuweiba.jpg', 'File:Dromadaire4478.jpg'], only: true },
  'trenggiling': { w: ['Sunda_pangolin'], img: ['File:Pangolin borneo.jpg', 'File:Manis javanica museum zoologicum bogoriense.png', 'File:Trenggiling Sunda Sunda Pangolin Manis javanica.jpg'], only: true },
  'walang-sangit': { w: ['Leptocorisa_oratoria'], img: ['File:Alydidae at Kadavoor.jpg', 'File:Leptocorisa oratorius-Kadavoor-2016-02-07-001.jpg', 'File:Walang Sangit (Leptocorisa sp.) di Taman Nasional Gunung Merapi.jpg', 'File:Leptocorisa acuta.jpg'], only: true },
  'owa-jawa': { w: ['Silvery_gibbon'], img: ['File:Moloch-20210525-Ctb.jpg', 'File:Silbergibbon mit Nachwuchs.jpg', 'File:Owa Jawa (Hylobates moloch).jpg'], only: true },
  'hydra': { w: ['Hydra_(genus)'], img: ['File:Hydra-Foto.jpg', 'File:Hydras (8).JPG', 'File:Hydra Budding.svg'], only: true },
  'tanaman-padi': { w: ['Rice'], img: ['File:20201102.Hengnan.Hybrid rice Sanyou-1.6.jpg', 'File:Koeh-232.jpg', 'File:Oryza sativa of Kadavoor.jpg'], only: true },
  'tanaman-mangga': { w: ['Mango'], img: ['File:Mangos - single and halved.jpg', 'File:Mango tree with fruit in Rincón, Puerto Rico.jpg', 'File:Mangifera indica pit.jpg'], only: true },
  'pohon-karet': { w: ['Hevea_brasiliensis', 'Natural_rubber'], img: ['File:Hevea brasiliensis - Köhler–s Medizinal-Pflanzen-071.jpg', 'File:Koh Chang, Thailand, Rubber tree.jpg'], only: true },
  'mawar': { w: ['Rose'], img: ['File:Rose Prickles.jpg', 'File:Roseleaves3800px.JPG', 'File:Roses Boutons FR 2012.jpg'], only: true },
  'kecambah': { w: ['Germination', 'Mung_bean'], img: ["File:Sequential Steps of Bean Seedling Germination.svg"], only: true },
  'tanaman-pisang': { w: ['Banana'], img: ['File:Banana corm.jpg', 'File:Young Banana Sapling - Kerala - IMG 3447.jpg'], only: true },
  'cangkok-okulasi-set': { w: ['Air_layering', 'Grafting'], img: ['File:Layer (PSF).png', 'File:Limonium dendroides air layering.jpg', 'File:Melograno margotta.jpg'], only: true },
  'pohon-jati': { w: ['Teak'], img: ['File:Nilambur Teak Plantation 0666.jpg', 'File:Plants of the coast of Coromandel Coast Tamil Nadu Andhra Pradesh India Flora Fruits Flowers (54).jpg'], only: true },
  'melinjo': { w: ['Gnetum_gnemon'], img: ['File:Gnetum Gnemon at Tasik Y Recreational Park.jpg', 'File:Gnetum gnemon.jpg', 'File:Melinjo2 (cropped).jpg'], only: true },
  'kantong-darah': { w: ['Blood_donation', 'Blood_bag'], img: [], only: true },
  'inhaler': { w: ['Metered-dose_inhaler'], img: ["File:MDI components.jpg"], only: true },
  'obat-set': { w: ['Tablet_(pharmacy)', 'Capsule_(pharmacy)'], img: ['File:FlattenedRoundPills.jpg', 'File:Four colors of pills.jpg'], only: true },
  'kutu-rambut': { w: ['Head_louse'], img: ["File:Male human head louse.jpg"], only: true },
  'nyamuk-anopheles': { w: ['Anopheles'], img: ["File:Anopheles stephensi.jpeg"], only: true },
  'ketapel': { w: ['Slingshot'], img: ["File:Slingshot (weapon).png"], only: true },
  'karet-gelang': { w: ['Rubber_band'], img: ["File:Rubber bands.jpg"], only: true },
  'ayunan': { w: ['Swing_(seat)'], img: ["File:Keswick Playground (Fitz Park).jpg"], only: true },
  'delman': { w: ['Delman'], img: ['File:Dokar parangtritis.jpg', 'File:Traditional betawi horsecar (Delman).jpg', 'File:"Andong" (horse-drawn carriage) on the road along Kuta Beach.jpg'], only: true },
  'komidi-putar': { w: ['Carousel', 'Ferris_wheel'], img: ['File:A double-decker carousel in Milton Keynes, England at Christmas.jpg', 'File:ManègeLR1.jpg'], only: true },
  'bendungan-plta': { w: ['Hydroelectricity', 'Dam'], img: ["File:ThreeGorgesDam-China2009.jpg"], only: true },
  'alat-listrik-rumah-set': { w: ['Home_appliance'], img: ["File:Breville.jpg", "File:Small appliance.jpg"], only: true },
  'sedotan-gelas-air': { w: ['Refraction'], img: ["File:Just a refraction.jpg"], only: true },
  'kapal-selam-sonar': { w: ['Sonar', 'Submarine'], img: [], only: true },
  'tebing-gema': { w: ['Echo'], img: ["File:William Henry Jackson - Echo Cliffs, Grand River Canyon - 2003.292 - Cleveland Museum of Art.tif"], only: true },
  'ambulans-doppler': { w: ['Doppler_effect', 'Ambulance'], img: ["File:Juli 2016 - Spoedtransport, Huisarts, Brandweer, Politie en Ambulances met spoed in Rotterdam -451.webm"], only: true },
  'gelombang-tali': { w: ['Transverse_wave'], img: ["File:Wave On Rope.png"], only: true },
  'air-mendidih': { w: ['Boiling'], img: ['File:Boilingkettle.jpg', 'File:Boiling water - close up (short shutter speed).ogv'], only: true },
  'gula-larut': { w: ['Solution_(chemistry)', 'Sugar'], img: ["File:SaltInWaterSolutionLiquid.jpg"], only: true },
  'molekul-set': { w: ['Ball-and-stick_model'], img: ["File:Water-3D-balls-A.png"], only: true },
  'unsur-logam-set': { w: ['Chemical_element'], img: [], only: true },
  'lemari-es': { w: ['Refrigerator'], img: ["File:Open refrigerator with food at night.jpg"], only: true },
  'gunung-meletus': { w: ['Stratovolcano', 'Mount_Merapi'], img: ['File:Subduction-en.svg', 'File:Etna from 2900m.jpg'], only: true },
  'gempa-patahan': { w: ['Earthquake', 'Hypocenter', 'Epicenter'], img: [], only: true },
  'tsunami': { w: ['Tsunami'], img: ['File:Eq-gen1.svg', 'File:Eq-gen3.svg', 'File:Eq-gen4.svg'], only: true },
  'banjir': { w: ['Flood'], img: ['File:Katrina-new-orleans-flooding3-2005.jpg', 'File:Rapid Creek flooding 1.jpg'], only: true },
  'kekeringan': { w: ['Drought'], img: ["File:Lac de l'Entonnoir - img 49473.jpg", 'File:Corn shows the effect of drought.jpg'], only: true },
  'awan-jenis-set': { w: ['Cloud', 'Cumulonimbus_cloud'], img: ["File:Sunrise In The Peak District.jpg"], only: true },
  'petir': { w: ['Lightning', 'Lightning_rod'], img: ['File:Port and lighthouse overnight storm with lightning in Port-la-Nouvelle.jpg', 'File:CC lightning, Albury NSW.JPG'], only: true },
  'pelangi': { w: ['Rainbow'], img: ["File:Double-alaskan-rainbow.jpg"], only: true },
  'siklus-air-diorama': { w: ['Water_cycle'], img: [], only: true },
  'sengkedan': { w: ['Terrace_(earthworks)', 'Tegallalang'], img: ['File:Haraz Mountains, Yemen (12633745063).jpg', 'File:Ruộng bậc thang Bản Phùng 1 - NKS.jpg'], only: true },
  'reboisasi': { w: ['Reforestation', 'Deforestation'], img: ["File:Reforestation 6 year.JPG"], only: true },
  'pencemaran-sungai': { w: ['Water_pollution'], img: ["File:Garbage floating around in Circular Quay.jpg"], only: true },
  'polusi-udara': { w: ['Air_pollution'], img: ["File:Air pollution3.jpg"], only: true },
  'hujan-asam': { w: ['Acid_rain'], img: ["File:Cloud formation from refinery in Curacao.jpg"], only: true },
  'rumah-kaca': { w: ['Greenhouse'], img: ["File:Botanical Garden V.L. Komarov Botanical Institute.jpg", "File:Flowers in a greenhouse.jpg"], only: true },
  'es-kutub-mencair': { w: ['Polar_bear', 'Sea_ice'], img: ["File:Polar Bear - Alaska (cropped).jpg"], only: true },
  'sampah-plastik-laut': { w: ['Marine_plastic_pollution', 'Microplastics'], img: ["File:Microplastics in sediment from the Rhine.jpg"], only: true },
  'terumbu-karang': { w: ['Coral_reef', 'Coral_bleaching'], img: ["File:Blue Linckia Starfish.JPG"], only: true },
  'pasang-surut-set': { w: ['Tide'], img: [], only: true },
  'aurora': { w: ['Aurora'], img: ['File:Aurora borealis over Eielson Air Force Base, Alaska.jpg', 'File:Flames in the sky.jpg'], only: true },
  'roket': { w: ['Rocket'], img: ["File:Soyuz TMA-9 launch.jpg"], only: true },
  'astronot': { w: ['Space_suit'], img: ['File:Berkut spacesuit.JPG', 'File:Yastreb suit.jpg'], only: true },
  'rasi-orion': { w: ['Orion_(constellation)'], img: ["File:OrionCC.jpg", "File:Orion 3008 huge.jpg"], only: true },
  'galaksi-bima-sakti': { w: ['Milky_Way', 'Barred_spiral_galaxy'], img: [], only: true },
  'pupuk-kompos-set': { w: ['Compost', 'Fertilizer'], img: ['File:Compost site germany.JPG', 'File:Composting in the Escuela Barreales.jpg', 'File:Compost pile.JPG'], only: true },
};
